### ISSUE TITLE
.dev version postfix breaks dev environment when version constraints are present

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter/nbconvert#1026]
Voila complains when I run it:
```
Traceback (most recent call last):
  File "/Users/maartenbreddels/miniconda3/envs/working/bin/voila", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/maartenbreddels/miniconda3/envs/working/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/Users/maartenbreddels/miniconda3/envs/working/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/Users/maartenbreddels/miniconda3/envs/working/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/maartenbreddels/miniconda3/envs/working/lib/python3.6/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/maartenbreddels/miniconda3/envs/working/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/maartenbreddels/miniconda3/envs/working/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nbconvert<6,>=5.5.0' distribution was not found and is required by voila
```
Which is a valid complain, since `5.5.0-dev` or `5.5.0.dev < 5.5.0` according to semver (and whatever is used in pkg_resources. 
This makes it annoying to work with the dev version of nbconvert. What would be the best way to avoid this, should after a 5.5.0 release the version be bumped to 5.5.1.dev maybe?

**Comment by MSeal** [comment]
That sounds reasonable. If making that change locally fixes it could you bump the version and update the relevant section in https://github.com/jupyter/nbconvert/blob/master/docs/source/development_release.rst#return-to-development-state ? I'll merge it if you confirm it works.

**Comment by t-makaro** [comment]
I noticed this too. I haven't encountered any issues, but it did seem weird not to be on ```5.5.1.dev``` since 5.5.0 is already released.
