### ISSUE TITLE
Creating and running the cells in a notebook with nteract scrapbook, but get AttributeError

### ISSUE THREAD

**Issue by victorluizgomes** [jupyter/nbconvert#1049]
I have ran some code that creates a notebook for me with some populated cells (which it works), but when I am trying to use ExecutePreprocessor to execute the cells that I put in the notebook, it gives me the error below. 

I do import scrapbook as sb, and if I open the notebook in Jupyter and execute the cell myself, the correct output comes out.

For some reason it does not recognize the scrapbook methods, I've also tried other scrapbook methods and it gives me the same error.

Any ideas on how to fix this or get around it would be much appreciated!
```
Traceback (most recent call last):
  File "/Users/vgomes/Documents/PROJECT NSRC/scraprunner.py", line 56, in <module>
    main()
  File "/Users/vgomes/Documents/PROJECT NSRC/scraprunner.py", line 50, in main
    ep.preprocess(nb, {'metadata': {'path': '.'}})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 381, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 424, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
    nb = sb.read_notebook('graph-test.ipynb')
    for name in nb.scraps.dataframe['name']:
        nb.reglue(name)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-dd7cc4bf7b2f>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mnb[0m [0;34m=[0m [0msb[0m[0;34m.[0m[0mread_notebook[0m[0;34m([0m[0;34m'graph-test.ipynb'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfor[0m [0mname[0m [0;32min[0m [0mnb[0m[0;34m.[0m[0mscraps[0m[0;34m.[0m[0mdataframe[0m[0;34m[[0m[0;34m'name'[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mnb[0m[0;34m.[0m[0mreglue[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'scrapbook' has no attribute 'read_notebook'
AttributeError: module 'scrapbook' has no attribute 'read_notebook'
```

**Comment by victorluizgomes** [comment]
Update, I think it had to do with the kernel/environment that I was executing the notebook in not having the right version of scrapbook. 

I copied my scripts to a different environment where I was sure the dependencies were present, and it works great.

**Comment by MSeal** [comment]
Glad to hear you got it resolved!
