### ISSUE TITLE
`nbconvert` Cell timeout errors don't print cell contents

### ISSUE THREAD

**Issue by rai-nhdaly** [jupyter/nbconvert#1123]
When a notebook cell times out, nbconvert stops with an error, as expected. However, the documentation says that it should print out _the contents of the cell that had the error_, but it does not:
> Conveniently, the source cell causing the error and the original error name and message are also printed.
- https://nbconvert.readthedocs.io/en/latest/execute_api.html#execution-until-first-error

EDIT: As described below, this is because the source cell doesn't _actually_ return an error, rather `nbconvert`'s monitoring errors. This Issue is to request that we change this behavior to still print the cell that timed out, as if the cell had errored. :) Thanks!

I believe this is because of this "exception while handling the exception":
> `During handling of the above exception, another exception occurred:`

A simple notebook that can reproduce this is a python notebook with just a single cell:
```
import time
time.sleep(10)
```

And then running `nbconvert` with a shorter timeout, e.g. `--ExecutePreprocessor.timeout=2`:
```bash
(15:29:05) $ ~/miniconda3/bin/jupyter nbconvert --to notebook --execute SleepTimeout-10.ipynb --ExecutePreprocessor.timeout=2
[NbConvertApp] WARNING | Config option `template_path` not recognized by `NotebookExporter`.
[NbConvertApp] Converting notebook SleepTimeout-10.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Timeout waiting for execute reply (2s).
Traceback (most recent call last):
  File "/Users/nathan.daly/miniconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 571, in run_cell
    if self._passed_deadline(deadline):
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 541, in _passed_deadline
    self._handle_timeout()
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 504, in _handle_timeout
    raise TimeoutError("Cell execution timed out")
TimeoutError: Cell execution timed out
```

EDIT: Updated the above output after updating to nbconvert 5.6.0. The original output can be found in a comment below.

Such a notebook is attached here:
[SleepTimeout-10.ipynb.txt](https://github.com/jupyter/nbconvert/files/3757464/SleepTimeout-10.ipynb.txt)

**Nbconvert version:** 5.6.0
```
$ ~/miniconda3/bin/jupyter nbconvert --version
5.6.0
```

---------------------------

Is there anything that can be done so that the culprit cell is still printed out? Why are there two exceptions occurring, the second occurring while handling the first?

**Comment by MSeal** [comment]
That is because the exception wasn't inside the cell -- it was inside nbconvert's monitoring of the cell. Though I do agree that printing out which cell timed out would be a nice error message improvement.

Also you're running a quite old version of nbconvert. The code involved with cell execution and timeouts was completely reworked at the beginning of this year, so the behavior may be a little different now in 5.6.

**Comment by rai-nhdaly** [comment]
> Also you're running a quite old version of nbconvert. The code involved with cell execution and timeouts was completely reworked at the beginning of this year, so the behavior may be a little different now in 5.6.

Ah, thanks, good catch! I've updated to 5.6, and indeed at least the "error within an error" is now gone:

```
(15:29:05) $ ~/miniconda3/bin/jupyter nbconvert --to notebook --execute SleepTimeout-10.ipynb --ExecutePreprocessor.timeout=2
[NbConvertApp] WARNING | Config option `template_path` not recognized by `NotebookExporter`.
[NbConvertApp] Converting notebook SleepTimeout-10.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Timeout waiting for execute reply (2s).
Traceback (most recent call last):
  File "/Users/nathan.daly/miniconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 571, in run_cell
    if self._passed_deadline(deadline):
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 541, in _passed_deadline
    self._handle_timeout()
  File "/Users/nathan.daly/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 504, in _handle_timeout
    raise TimeoutError("Cell execution timed out")
TimeoutError: Cell execution timed out
```

> That is because the exception wasn't inside the cell -- it was inside nbconvert's monitoring of the cell. Though I do agree that printing out which cell timed out would be a nice error message improvement.

I see, thanks. Then, yeah, can we make that change? :) I'll re-word my original comment

**Comment by MSeal** [comment]
I'm not likely to get to this myself soon, but the ExecutePreprocessor has a `TimeoutError` that could be enhanced -- I maybe wouldn't print the whole cell contents in the stack trace but maybe the `first 5 ... last 5` lines could be useful, or perhaps just the cell index.

**Comment by rai-nhdaly** [comment]
Thanks, btw, @MSeal! :)
