### ISSUE TITLE
nbconvert to pdf error

### ISSUE THREAD

**Issue by HighTechLord** [jupyter/nbconvert#1156]
When I try to convert my jupyter notebook hw4_dry_empty.ipynb to pdf I got this error:
```
(base) C:\Users\User>jupyter nbconvert hw4_dry_empty.ipynb --to pdf
[NbConvertApp] Converting notebook hw4_dry_empty.ipynb to pdf
[NbConvertApp] Support files will be in hw4_dry_empty_files\
[NbConvertApp] Making directory .\hw4_dry_empty_files
[NbConvertApp] Making directory .\hw4_dry_empty_files
[NbConvertApp] Writing 39210 bytes to .\notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', '.\\notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | x failed: xelatex .\notebook.tex -quiet

Sorry, but C:\Users\User\Anaconda3\Library\miktex\texmfs\install\miktex\bin\xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/User/AppData/Local/MiKTeX/2.9/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.

Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\User\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\User\Anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 185, in from_notebook_node
    self.run_latex(tex_file)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 156, in run_latex
    self.latex_count, log_error, raise_on_failure)
  File "C:\Users\User\Anaconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 145, in run_command
    command=command, output=out))
nbconvert.exporters.pdf.LatexFailed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:

Sorry, but C:\Users\User\Anaconda3\Library\miktex\texmfs\install\miktex\bin\xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/User/AppData/Local/MiKTeX/2.9/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.

```
And that I got when I try to convert by the jupyter:
```
500 : Internal Server Error
The error was:
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:

Sorry, but C:\Users\User\Anaconda3\Library\miktex\texmfs\install\miktex\bin\xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/User/AppData/Local/MiKTeX/2.9/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help
```
When I convert to something else, including .tex, I don't have a problem

**Comment by t-makaro** [comment]
You're missing LaTeX as a dependency. You can find information about installing it on our  [docs](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex).

**Comment by HighTechLord** [comment]
@t-makaro no, I installed it:
`(base) C:\Users\User>conda install -c conda-forge/label/cf201901 miktex
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.`

**Comment by t-makaro** [comment]
It XeLaTeX available in your path?

Can you compile a .tex file manually?

**Comment by HighTechLord** [comment]
@t-makaro yeah, I ran MixTex manually and solved the problem.
