### ISSUE TITLE
nbconvert --to pdf

### ISSUE THREAD

**Issue by arnold-c** [jupyter/nbconvert#1170]
Hi,

I know this is a common issue, but unfortunately none of the previous solutions seem to be able to help my issue. I recently made a fresh install of miniconda (Py3.7.4) on Windows 10 (64 bit), and I can't get nbconvert to work when converting a notebook to pdf. I used `anaconda-clean`, so it should be a clean install, and hopefully no interactions with lingering packages etc.

I think these are all the relevant details about OS/packages.

```
(base) C:\Users\owner\test>systeminfo

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18362 N/A Build 18362
System Type:               x64-based PC

(base) C:\Users\owner\test>conda list
# packages in environment at C:\Users\owner\Miniconda3:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl
absl-py                   0.8.1                    py37_0
asn1crypto                1.2.0                    py37_0
astor                     0.8.0                    py37_0
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py37_0
beautifulsoup4            4.8.2                    pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
colorama                  0.4.3                      py_0
conda                     4.8.1                    py37_0
conda-package-handling    1.6.0            py37h62dcd97_0
console_shortcut          0.1.1                         3
cryptography              2.8              py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
epipy                     0.0.2.1                  pypi_0    pypi
flake8                    3.7.9                    py37_0
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                    py37_0
google-pasta              0.1.8                      py_0
grpcio                    1.16.1           py37h351948d_1
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
importlib_metadata        1.3.0                    py37_0
inkscape                  0.91                          0    conda-forge
intel-openmp              2019.4                      245
ipykernel                 5.1.3            py37h39e3cac_0
ipystata                  0.3.8                    pypi_0    pypi
ipython                   7.11.1           py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.2                   py37_0
jinja2                    2.10.3                     py_0
joblib                    0.14.1                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.8.5                      py_0
jsonschema                3.2.0                    py37_0
jupyter_client            5.3.4                    py37_0
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.6.1                    py37_0
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterlab                1.2.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
jupyterthemes             0.20.0                   pypi_0    pypi
keras-applications        1.0.8                      py_0
keras-preprocessing       1.1.0                      py_1
kiwisolver                1.1.0            py37ha925a31_0
lesscpy                   0.13.0                   pypi_0    pypi
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libmklml                  2019.0.5                      0
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.11.2               h7bd577a_0
libsodium                 1.0.16               h9d3ae62_0
libxml2                   2.9.10               h9ce36c8_0    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
lxml                      4.4.2            py37heafd4d3_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.1            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
more-itertools            8.0.2                      py_0
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py37_0
nbformat                  4.4.0                    py37_0
networkx                  1.8.1                    pypi_0    pypi
nodejs                    12.12.0                       0    conda-forge
notebook                  6.0.2                    py37_0
numpy                     1.17.4           py37h4320e6b_0
numpy-base                1.17.4           py37hc3f5095_0
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
opt_einsum                3.1.0                      py_0
packaging                 19.2                     pypi_0    pypi
pandas                    0.25.3           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.5.2                      py_0
pathlib                   1.0.1                    py37_1
patsy                     0.5.1                    py37_0
pexpect                   4.7.0                    pypi_0    pypi
pickleshare               0.7.5                    py37_0
pillow                    7.0.0                    pypi_0    pypi
pip                       19.3.1                   py37_0
plotly                    4.4.1                      py_0
ply                       3.11                     pypi_0    pypi
powershell_shortcut       0.0.1                         2
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.2                      py_0
protobuf                  3.11.2           py37h33f27b4_0
psutil                    5.6.7            py37he774522_0
ptyprocess                0.6.0                    pypi_0    pypi
py4epi                    0.1                       dev_0    <develop>
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.19                     py37_0
pyflakes                  2.1.1                    py37_0
pygments                  2.5.2                      py_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyprojroot                0.2.0                      py_0    conda-forge
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.15.6           py37he774522_0
pysocks                   1.7.1                    py37_0
python                    3.7.4                h5263a28_0
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pywin32                   227              py37he774522_0
pywinpty                  0.5.7                    py37_0
pyyaml                    5.1.2            py37hfa6e2cd_0    conda-forge
pyzmq                     18.1.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
requests                  2.22.0                   py37_1
researchpy                0.1.8            py37h39e3cac_0    researchpy
retrying                  1.3.3                    py37_2
ruamel_yaml               0.15.87          py37he774522_0
scikit-learn              0.22             py37h6288b17_0    anaconda
scipy                     1.3.2            py37h29ff71c_0
seaborn                   0.9.0              pyh91ea838_1
send2trash                1.5.0                    py37_0
setuptools                44.0.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.13.0                   py37_0
soupsieve                 1.9.5                    pypi_0    pypi
sqlite                    3.30.1               he774522_0
stata-kernel              1.10.5                   pypi_0    pypi
statsmodels               0.10.1           py37h8c2d366_0
tensorboard               2.0.0              pyhb38c66f_1
tensorflow                2.0.0           mkl_py37he1bbcac_0
tensorflow-base           2.0.0           mkl_py37hd1d5974_0
tensorflow-estimator      2.0.0              pyh2649769_0
termcolor                 1.1.0                    py37_1
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tornado                   6.0.3            py37he774522_0
tqdm                      4.40.2                     py_0
traitlets                 4.3.3                    py37_0
urllib3                   1.25.7                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zipp                      0.6.0                      py_0
zlib                      1.2.11               h62dcd97_3
```

Below is the command I use in the miniconda prompt, with the following error

```
(base) C:\Users\owner\test>jupyter nbconvert --to pdf test.ipynb
[NbConvertApp] Converting notebook test.ipynb to pdf
The system cannot find the path specified.
[NbConvertApp] Support files will be in test_files\
[NbConvertApp] Making directory .\test_files
[NbConvertApp] Making directory .\test_files
[NbConvertApp] Making directory .\test_files
[NbConvertApp] Writing 24727 bytes to .\notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', '.\\notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | x failed: xelatex .\notebook.tex -quiet
The system cannot find the path specified.

Traceback (most recent call last):
  File "C:\Users\owner\Miniconda3\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\owner\Miniconda3\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\owner\Miniconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 185, in from_notebook_node
    self.run_latex(tex_file)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 156, in run_latex
    self.latex_count, log_error, raise_on_failure)
  File "C:\Users\owner\Miniconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 145, in run_command
    command=command, output=out))
nbconvert.exporters.pdf.LatexFailed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
The system cannot find the path specified.
```
I get a similar issue when I use the Notebook GUI

![image](https://user-images.githubusercontent.com/24391445/72556858-8a3bff80-386d-11ea-9c24-470f6bf8ed2b.png)

I do not have miniconda in my PATH (when editing through the Control Panel), but adding it made no difference, so I would rather not add it unless necessary. I do have MiKTeX in my PATH, and when I type `xelatex` into the command prompt/miniconda prompt it recognises the command. The only odd thing is that in the command prompt, `echo %PATH%` returns `...\Miniconda3\...`, whereas it doesn't in Git Bash. Otherwise, they are the same (I've included the start of each for reference). Could this have something to do with it, and if so, is there a way to solve this issue?

```
(base) C:\Users\owner\test>echo %PATH% | tr ":" "\n"
C
\Users\owner\Miniconda3;C
\Users\owner\Miniconda3\Library\mingw-w64\bin;C
\Users\owner\Miniconda3\Library\usr\bin;C
\Users\owner\Miniconda3\Library\bin;C
\Users\owner\Miniconda3\Scripts;C
\Users\owner\Miniconda3\bin;C
\Users\owner\Miniconda3\condabin;C
\Users\owner\Miniconda3\lib\site-packages\pywin32_system32;C
\Users\owner\Miniconda3;C
\Users\owner\Miniconda3\Library\mingw-w64\bin;C
\Users\owner\Miniconda3\Library\usr\bin;C
\Users\owner\Miniconda3\Library\bin;C
\Users\owner\Miniconda3\Scripts;C
\Users\owner\Miniconda3\bin;C
\Perl64\bin;C
\Rtools\bin;C
...
\Program Files\MiKTeX 2.9\miktex\bin\x64;C
...
\Program Files\Inkscape;C
...
```

```
owner MINGW64 ~
$ echo $PATH | tr ":" "\n"
/c/Users/owner/bin
/mingw64/bin
/usr/local/bin
/usr/bin
/bin
/mingw64/bin
/usr/bin
/c/Users/owner/bin
/c/Perl64/bin
/c/Rtools/bin
/bin
...
/c/Program Files/MiKTeX 2.9/miktex/bin/x64
...
/c/Program Files/Inkscape
...
```

Unlike #326 I am using the commands in the same directory for input and outputs.

Like #1156 I can use nbconvert to create the relevant tex files and compile manually, but it would be nice not to have to go through this extra step (`jupyter nbconvert --to latex test.ipynb` works).

Any advice would be greatly appreciated!

**Comment by oholimoli** [comment]
I have also the same Problem. :/

![latex](https://user-images.githubusercontent.com/47213738/74435355-89928b00-4e64-11ea-95d1-51d5fec12455.PNG)

When I try to convert first to tex and then to latex I get other errors:

```
! Extra alignment tab has been changed to \cr.
<recently read> \endtemplate

l.458  x_0^M & x_0^{M-1} &
                           \cdots & x_0 & 1  \\
?
! Emergency stop.
<recently read> \endtemplate

l.458  x_0^M & x_0^{M-1} &
                           \cdots & x_0 & 1  \\
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by noamza** [comment]
I also have this problem

**Comment by oltip** [comment]
Had anybody solved this issue? 
I am trying to solve it  over the last week, but without success.

**Comment by oltip** [comment]
Had anybody solved this issue?
I have been trying to solve it over the last week, but without success.

**Comment by MSeal** [comment]
No unfortunately, I've not been able to get the significant time to refactor the pdf conversion code for the 6.0 release. It's on the roadmap but the complexity and tooling limitations herein make it really challenging to avoid all edges cases, especially when there's working directory and additional files involved.

**Comment by noamza** [comment]
Thank you for the response. I think I exported my notebook to html and/or used my browser's print to pdf function, which is all a bit clunky but got the job done. Thank you for your work!

**Comment by yuliaUU** [comment]
I got this iissue:
```
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
? 
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.
```

**Comment by christian-cahig** [comment]
> I got this iissue:
> 
> ```
> nbconvert failed: PDF creating failed, captured latex output:
> Failed to run "xelatex .\notebook.tex -quiet" command:
> This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
>  restricted \write18 enabled.
> entering extended mode
> ! Undefined control sequence.
> <*> .\notebook
>               .tex -quiet
> ? 
> ! Emergency stop.
> <*> .\notebook
>               .tex -quiet
> No pages of output.
> Transcript written on ?.
> ```

I have the same issue.

**Comment by yuliaUU** [comment]
@christian-cahig You have two options:
1. remove  all folders that have ncbconverter and run `pip install https://github.com/jupyter/nbconvert/archive/6.0.0a6.zip`
2. A temporary remedy (could break other things) is to change the build directory in pdf.py from nbconvert (line 66) from
`writer = Instance("nbconvert.writers.FilesWriter", args=(), kw={'build_directory': '.'})
`
to
`writer = Instance("nbconvert.writers.FilesWriter", args=(), kw={'build_directory': ''})`

**Comment by yuliaUU** [comment]
> > I got this iissue:
> > ```
> > nbconvert failed: PDF creating failed, captured latex output:
> > Failed to run "xelatex .\notebook.tex -quiet" command:
> > This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
> >  restricted \write18 enabled.
> > entering extended mode
> > ! Undefined control sequence.
> > <*> .\notebook
> >               .tex -quiet
> > ? 
> > ! Emergency stop.
> > <*> .\notebook
> >               .tex -quiet
> > No pages of output.
> > Transcript written on ?.
> > ```
> 
> I have the same issue.

@christian-cahig You have two options:
1. remove  all folders that have ncbconverter and run `pip install https://github.com/jupyter/nbconvert/archive/6.0.0a6.zip`
2. A temporary remedy (could break other things) is to change the build directory in pdf.py from nbconvert (line 66) from
`writer = Instance("nbconvert.writers.FilesWriter", args=(), kw={'build_directory': '.'})
`
to
`writer = Instance("nbconvert.writers.FilesWriter", args=(), kw={'build_directory': ''})`


I tried both, and only 1st solution worked

**Comment by christian-cahig** [comment]
@yuliaUU none of them worked for me :( Anyway, thanks for these suggestions. I hope this issue gets resolved soon.

**Comment by yuliaUU** [comment]
> @yuliaUU none of them worked for me :( Anyway, thanks for these suggestions. I hope this issue gets resolved soon.

Did you removed all the nbconverter folders? I had like 5-6 places where I had the folder called that way, so had to remove it, also if you have other previous versions that may cause issues too

**Comment by t-makaro** [comment]
@christian-cahig @yuliaUU Alternatively you can download MikTeX from here: https://miktex.org/download instead of using TeX Live. You will need to uninstall TeX Live.

**Comment by yuliaUU** [comment]
@t-makaro I tried MikTex, as I used to use it for working in R, it did not work for converting python notebooks in jupyter

**Comment by t-makaro** [comment]
@yuliaUU You might need a few attempts of running miktex to get it to work, as miktex has to download some extra packages to compile. Converting your notebook ```--to latex``` and then convert with ```xelatex filename.tex``` manually. You should see a bunch of prompts to install packages.

**Comment by yuliaUU** [comment]
@t-makaro thanks. A lot!
