### ISSUE TITLE
Using any template results in "ValueError: Unsupported mimetype"

### ISSUE THREAD

**Issue by marnec** [jupyter/nbconvert#1184]
When launching nbconvert --to any format {pdf,html,...}, if a template is passed through the --template option, nbconvert will crash with error:

```
ValueError: Unsupported mimetype 'text/{pdf,html,...}' for template 'hidecode.tplx', mimetypes supported are: 
<empty line>
```
 
I'm working on Ubuntu 18, in a pipenv environment with python 3.6.9. Virtual environment is installed in project folder. The problem presents itself even when deleting and reinstalling the whole environment. The problem presents itself with any template file/folder (including default templates like article.tplx)

**Nbconvert version:** 6.0.0a0

**Comment by MSeal** [comment]
So templates are a organized a little differently in the 6.0 pre-release version than in 5.x. Templates now use directories as the template name, organized inside with an `index.<format>.j2` file and several supporting files to build the output.

For example, jupyter lab has a template which can be referred to by

```bash
jupyter nbconvert my_nb.ipynb --to html --template lab
```

If the command above isn't working for you then someone else is wrong and you'll want to run with `--log-level DEBUG` and maybe give us more information on your current venv dependencies.

**Comment by maartenbreddels** [comment]
I guess we can improve on the error msg on what is going on. I guess this happens: It looks for the template directory with that name, collects all conf.json files (it will find none) and also will not find mimetypes, which it prints out.

**Comment by MSeal** [comment]
I would definitely say we should improve error messaging around this and/or see if the backwards compatibility fixes could help with it.

I'm planning on making the PR to use nbclient and delete most of the execute proprocessor code later this week after which I can give more attention to messaging and comparability improvements before the major release (don't want that to stretch indefinitely).

**Comment by ogiorgis** [comment]
Same problem for me:

```
>> jupyter nbconvert file.ipynb --to pdf 

ValueError: Unsupported mimetype 'text/{pdf,html,...}' for template 'hidecode.tplx', mimetypes supported are: 
<empty line>
```

```
>> jupyter nbconvert file.ipynb --to pdf --template lab

ValueError: No template sub-directory with name 'lab' found in the following paths:
        /home/ogiorgis/.local/share/jupyter
        /home/ogiorgis/Tools/python/envs/jupyterlab-2.0/share/jupyter
        /usr/local/share/jupyter
        /usr/share/jupyter

```
and 

```
>> ls /home/ogiorgis/Tools/python/envs/jupyterlab-2.0/share/jupyter/lab/
extensions  imports.css  schemas  settings  staging  static  themes

```
Nbconvert version: 6.0.0a0

Regards

**Comment by MSeal** [comment]
This should be fixed in a3 release, with some additional fixes about to land for the final push to 6.0

**Comment by gabemorris12** [comment]
I'm having the same issue. Is this issue still not fixed or could there be something wrong on my end?

### My Environment
***
```
jupyter nbconvert --version
6.1.0
```
```
python --version
Python 3.9.6
```
### Traceback
***
```
Traceback (most recent call last):
  File "c:\python-3.9.6\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python-3.9.6\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python-3.9.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python-3.9.6\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "c:\python-3.9.6\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\python-3.9.6\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "c:\python-3.9.6\lib\site-packages\nbconvert\nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "c:\python-3.9.6\lib\site-packages\nbconvert\nbconvertapp.py", line 513, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "c:\python-3.9.6\lib\site-packages\nbconvert\exporters\templateexporter.py", line 330, in __init__
    super().__init__(config=config, **kw)
  File "c:\python-3.9.6\lib\site-packages\nbconvert\exporters\exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "c:\python-3.9.6\lib\site-packages\nbconvert\exporters\templateexporter.py", line 497, in _init_preprocessors
    conf = self._get_conf()
  File "c:\python-3.9.6\lib\site-packages\nbconvert\exporters\templateexporter.py", line 515, in _get_conf
    for path in map(Path, self.template_paths):
  File "c:\python-3.9.6\lib\site-packages\traitlets\traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "c:\python-3.9.6\lib\site-packages\traitlets\traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "c:\python-3.9.6\lib\site-packages\traitlets\traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "c:\python-3.9.6\lib\site-packages\traitlets\traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "c:\python-3.9.6\lib\site-packages\nbconvert\exporters\templateexporter.py", line 526, in _template_paths
    template_names = self.get_template_names()
  File "c:\python-3.9.6\lib\site-packages\nbconvert\exporters\templateexporter.py", line 616, in get_template_names
    raise ValueError('Unsupported mimetype %r for template %r, mimetypes supported are: \n\t%s' %\
ValueError: Unsupported mimetype 'application/pdf' for template 'classic', mimetypes supported are:
        text/html
```
I did run a `--log-level DEBUG` tag, but it was not very helpful.
