### ISSUE TITLE
need correct syntax to configure c.TemplateExporter.template_path

### ISSUE THREAD

**Issue by phaustin** [jupyter/nbconvert#1186]
I'm trying to follow https://nbconvert.readthedocs.io/en/latest/customizing.html#Saving-Custom-Templates  with the current master and am unable to make a template folder accessible to nbconvert.

Specifically, I'm doing the following with an editable install:

1) from the cloned directory:

```
cd nbconvert/share/jupyter/nbconvert/template
cp -a classic newclassic
cp -a classic ~/.jupyter/custom/html/newclassic2
```

2)  put the following lines in ~/.jupyter/jupyter_nbconvert_config.py:
```
from pathlib import Path
homedir = Path().home()
latex_templates = str(homedir / ".jupyter/custom/latex/")
html_templates = str(homedir / ".jupyter/custom/html")
target_list = ['.', latex_templates, html_templates]
print(f"my target path list: {target_list}")
target_template = Path(html_templates) / 'newclassic2'
print(f"check for template existence: {target_template.is_dir()}")
c.TemplateExporter.template_path = target_list
from jupyter_core.paths import jupyter_path
print(f"here is my path: {jupyter_path('nbconvert','templates')}")
```

3) If I then take a sample notebook and do:
```
jupyter nbconvert --to html day5_quiz_students.ipynb --template=newclassic
```
I get a successful write of an a html file.

4) If instead I do:

```
jupyter nbconvert --to html day5_quiz_students.ipynb --template=newclassic2
```
nbconvert fails with:

```
my target path list: ['.', '/Users/phil/.jupyter/custom/latex', '/Users/phil/.jupyter/custom/html']
check for template existence: True
here is my path: ['/Users/phil/Library/Jupyter/nbconvert/templates', '/Users/phil/a50037/envs/e213/share/jupyter/nbconvert/templates', '/usr/local/share/jupyter/nbconvert/templates', '/usr/share/jupyter/nbconvert/templates']
[NbConvertApp] Converting notebook day5_quiz_students.ipynb to html
Traceback (most recent call last):
  File "/Users/phil/a50037/envs/e213/bin/jupyter-nbconvert", line 11, in <module>
    load_entry_point('nbconvert', 'console_scripts', 'jupyter-nbconvert')()
  File "/Users/phil/a50037/envs/e213/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/phil/a50037/envs/e213/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/phil/repos/nbconvert/nbconvert/nbconvertapp.py", line 341, in start
    self.convert_notebooks()
  File "/Users/phil/repos/nbconvert/nbconvert/nbconvertapp.py", line 511, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/phil/repos/nbconvert/nbconvert/nbconvertapp.py", line 482, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/Users/phil/repos/nbconvert/nbconvert/nbconvertapp.py", line 411, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/html.py", line 103, in from_notebook_node
    self.register_filter('highlight_code', highlight_code)
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/templateexporter.py", line 418, in register_filter
    return self._register_filter(self.environment, name, jinja_filter)
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/templateexporter.py", line 154, in environment
    self._environment_cached = self._create_environment()
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/templateexporter.py", line 436, in _create_environment
    paths = self.get_template_paths()
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/templateexporter.py", line 465, in get_template_paths
    template_names = self.get_template_names()
  File "/Users/phil/repos/nbconvert/nbconvert/exporters/templateexporter.py", line 512, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (template_name, paths))
ValueError: No template sub-directory with name 'newclassic2' found in the following paths:
	/Users/phil/repos/nbconvert/share/jupyter
	/Users/phil/Library/Jupyter
	/Users/phil/a50037/envs/e213/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter
```

What should I be putting in my jupyter_nbconvert_config.py?

thanks, Phil

**Comment by phaustin** [comment]
superseeded by #1188
