### ISSUE TITLE
InkScape Executable Not Found while converting multiple ipynb files

### ISSUE THREAD

**Issue by ahmadmustafaanis** [jupyter/nbconvert#1208]
I am trying to convert multiple ipynb files to pdf cloned from a git repositroy . I named all of them in a script as given in documentation like this
`c = get_config()
c.NbConvertApp.notebooks = ["01_intro.ipynb", "02_production.ipynb", "03_ethics.ipynb", "04_mnist_basics.ipynb", "05_pet_breeds.ipynb", "06_multicat.ipynb", "07_sizing_and_tta.ipynb" ,"08_collab.ipynb" ,"09_tabular.ipynb", "10_nlp.ipynb" ,"11_nlp_dive.ipynb", "12_better_rnn.ipynb", "13_convolutions.ipynb", "14_deep_conv.ipynb", "15_resnet.ipynb", "16_arch_details.ipynb"," 17_accel_sgd.ipynb", "18_callbacks.ipynb","19_foundations.ipynb" ,"20_CAM.ipynb", "21_learner.ipynb" ,"22_conclusion.ipynb", "app_blog.ipynb", "app_jupyter.ipynb"]`
When I run command
`jupyter nbconvert --config mcfig.py --to pdf`
or 
`jupyter nbconvert --config mcfig.py --to pdf --allow-errors`
I get following error

`[NbConvertApp] Converting notebook 01_intro.ipynb to pdf
Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'inkscape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 67, in _inkscape_default
    rkey = winreg.OpenKey(wr_handle, "SOFTWARE\\Classes\\inkscape.svg\\DefaultIcon")
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "F:\Anaconda\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "F:\Anaconda\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\pdf.py", line 171, in from_notebook_node
    nb, resources=resources, **kw
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\latex.py", line 88, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\convertfigures.py", line 46, in preprocess_cell
    self.from_format, output.data[self.from_format])
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 91, in convert_figure
    shell = self.command.format(from_filename=input_filename,
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 55, in _command_default
    return self.inkscape + \
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 70, in _inkscape_default
    raise FileNotFoundError("Inkscape executable not found")
FileNotFoundError: Inkscape executable not found

C:\Users\Ahmad Anis\Desktop\FASTAI_BOOK\fastbook>jupyter nbconvert --config mcfig.py --to pdf --allow-errors
[NbConvertApp] Converting notebook 01_intro.ipynb to pdf
Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'inkscape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 67, in _inkscape_default
    rkey = winreg.OpenKey(wr_handle, "SOFTWARE\\Classes\\inkscape.svg\\DefaultIcon")
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "F:\Anaconda\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "F:\Anaconda\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "F:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\pdf.py", line 171, in from_notebook_node
    nb, resources=resources, **kw
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\latex.py", line 88, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "F:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\convertfigures.py", line 46, in preprocess_cell
    self.from_format, output.data[self.from_format])
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 91, in convert_figure
    shell = self.command.format(from_filename=input_filename,
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 55, in _command_default
    return self.inkscape + \
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 70, in _inkscape_default
    raise FileNotFoundError("Inkscape executable not found")
FileNotFoundError: Inkscape executable not found`

I tried pip install Inkscape but it didnt worked

**Nbconvert version:**

**Comment by MSeal** [comment]
Inkscape isn't a python package, it's a separate software offering: https://inkscape.org/release/0.92.4/windows/64-bit/

**Comment by MSeal** [comment]
Closing, ping if there's more concern / questions
