### ISSUE TITLE
Cannot export to PDF but tex export works | Error: xelatex not found in path

### ISSUE THREAD

**Issue by Maccer1** [jupyter/nbconvert#1248]
* Using anaconda 2020.02 with Jupyter Lab 1.2.6,  Pandoc 2.2.3.2 and Miktex 2.9.7414. 
* Windows 10
* Miktex was installed as an standalone program for only one user (I didn't use the conda-forge version).
* The Miktex version from conda-forge trows a different issue. I won't enter in details since I think that should be another bug report.
* I can export to .tex and then use TEXworks to convert to pdf
* I cannot export to .pdf using nbconvert. "Error: xelatex not found in path"
* My windows Path points to ` C:\Users\nicol\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\ ` and ` C:\Users\nicol\MiKTeX\miktex\bin\x64\ `

Go to JupyterLab, open a notebook with just Markdown and export it to PDF. Does not work.

[Untitled.ipynb](https://github.com/jupyter/nbconvert/files/4576993/Untitled.txt)

**Nbconvert version:** 5.6.1

Console output: 

``` 
(Default) C:\Users\nicol>jupyter nbconvert --to pdf Untitled.ipynb
[NbConvertApp] Converting notebook Untitled.ipynb to pdf
[NbConvertApp] Writing 20652 bytes to .\notebook.tex
[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "C:\Users\nicol\Anaconda3\envs\Default\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\exporters\pdf.py", line 185, in from_notebook_node
    self.run_latex(tex_file)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\exporters\pdf.py", line 156, in run_latex
    self.latex_count, log_error, raise_on_failure)
  File "C:\Users\nicol\Anaconda3\envs\Default\lib\site-packages\nbconvert\exporters\pdf.py", line 114, in run_command
    "at {link}.".format(formatter=command_list[0], link=link))
OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
```

**Comment by t-makaro** [comment]
Have you restarted your Jupyter server since installing MikTeX? What happens if you open a new cmd and convert the notebook from there?
```cmd
jupyter nbconvert --to pdf <notebookname>
```

**Comment by Maccer1** [comment]
>Have you restarted your Jupyter server since installing MikTeX? 
Oops that was it. Now it works. I did a full system reboot.
