### ISSUE TITLE
Conversion fails when path to notebook contains regex syntax

### ISSUE THREAD

**Issue by THargreaves** [jupyter/nbconvert#1293]
I have a Jupyter notebook `presentation.ipynb` in a directory with a title such as `Foobar Talk [2020-06-23]`. From this directory I run `jupyter nbconvert presentation.ipynb --to slides`. This results in the following error:

```
Traceback (most recent call last):
  File "/home/tim/miniconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/tim/miniconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/tim/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/tim/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/tim/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 499, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/home/tim/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 98, in get_exporter
    return entrypoints.get_single('nbconvert.exporters', name).load()
  File "/home/tim/miniconda3/lib/python3.7/site-packages/entrypoints.py", line 211, in get_single
    for config, distro in iter_files_distros(path=path):
  File "/home/tim/miniconda3/lib/python3.7/site-packages/entrypoints.py", line 189, in iter_files_distros
    glob.iglob(osp.join(folder, '*.egg-info', 'entry_points.txt'))
  File "/home/tim/miniconda3/lib/python3.7/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/home/tim/miniconda3/lib/python3.7/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/home/tim/miniconda3/lib/python3.7/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/home/tim/miniconda3/lib/python3.7/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/home/tim/miniconda3/lib/python3.7/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/home/tim/miniconda3/lib/python3.7/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/home/tim/miniconda3/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/home/tim/miniconda3/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/tim/miniconda3/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/tim/miniconda3/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/tim/miniconda3/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/home/tim/miniconda3/lib/python3.7/sre_parse.py", line 810, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/home/tim/miniconda3/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/home/tim/miniconda3/lib/python3.7/sre_parse.py", line 574, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range 6-2 at position 39
```

It would appear that `re` is picking up on the date in the containing directory, and since this is in square brackets, trying to generate the range `6-2` and failing.

I tested this with an empty notebook and the error still persists. Removing the date from the directory fixes this. Obviously, now that I've discovered this I can just format my date differently and ignore this but this does make me wonder what other issues will exist since the path to the file is not being escaped for regex.

**Nbconvert version:** 5.6.1

**Comment by MSeal** [comment]
Looks like we need to capture and escape regex characters before they go to the glob function from the exporter search code in `get_exporter`. Thanks for raising, I'll add it to the list of bugs to address in the 6.0 -- though would love if you or someone else also had time to try and submit a patch for it.

**Comment by t-makaro** [comment]
I'm not sure that I quite understand. Is the glob/regex syntax in the directory name or the title of the notebook?

If the glob is a path to the notebook, then this is a duplicate of #911. You need to escape the path which can be done by adding an extra ```[]``` around the first ```[``` (using pythons built-in regex escaper I found this solution for someone else). Dev Note: This is caused by this section: https://github.com/jupyter/nbconvert/blob/606c18437c2371799dfc692fffaed88e781af3f9/nbconvert/nbconvertapp.py#L291 Though wouldn't it have to be converting the relative path to a absolute path at some point?

If this is in the title of a notebook, then I have no clue what is happening.

**Comment by THargreaves** [comment]
It's in the directory name. Feel free to close in that case.
