### ISSUE TITLE
ImportError: No module named post_embedhtml

### ISSUE THREAD

**Issue by rabernat** [jupyter/nbconvert#138]
I recently upgraded to jupyter version 4.0.4 via anaconda.

I am now totally unable to use jupyter nbconvert.

```python
jupyter nbconvert profile.ipynb
```

produces the following cryptic error:
```
[NbConvertApp] WARNING | Error loading config file: jupyter_nbconvert_config
Traceback (most recent call last):
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 202, in load_config_file
    path=path
  File "<string>", line 2, in load_config_file
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in load_config_file
    self.update_config(config)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 410, in update_config
    self.config = newconfig
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 465, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 683, in _notify_trait
    c(name, old_value, new_value)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 249, in _config_changed
    SingletonConfigurable._config_changed(self, name, old, new)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 170, in _config_changed
    self._load_config(new, traits=traits, section_names=section_names)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 154, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/Users/rpa/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 645, in hold_trait_notifications
    self._notify_trait(*v)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 683, in _notify_trait
    c(name, old_value, new_value)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 201, in _postprocessor_class_changed
    self.postprocessor_factory = import_item(new)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named post_embedhtml
Traceback (most recent call last):
  File "/Users/rpa/anaconda/bin/jupyter-nbconvert", line 6, in <module>
    main()
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 222, in initialize
    self.init_postprocessor()
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 277, in init_postprocessor
    self.postprocessor_class)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 201, in _postprocessor_class_changed
    self.postprocessor_factory = import_item(new)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named post_embedhtml
```

**Comment by juhasch** [comment]
`post_embedhtml.py` is part of the IPython-contrib notebook extensions. You need to install them in Jupyter or remove the reference to it in your nbconvert configuration.

**Comment by rabernat** [comment]
> You need to install them in Jupyter or remove the reference to it in your nbconvert configuration.

@juhasch thanks for the tip. I don't know how to do either option unfortunately.
