### ISSUE TITLE
Exporters fail to pickle in nbconvert >= 6

### ISSUE THREAD

**Issue by kycutler** [jupyter/nbconvert#1398]
With nbconvert version 5 I was able to invoke exporters via a process pool. After upgrading to nbconvert >= 6.0.0 I get the error `AttributeError: Can't pickle local object 'TemplateExporter._init_resources.<locals>.deprecated`.

Repro (python 3.7):

```python
import nbconvert, nbformat
from concurrent.futures import ProcessPoolExecutor

if __name__ == "__main"":
  executor = ProcessPoolExecutor()
  exporter = nbconvert.exporters.PythonExporter()
  nb = nbformat.read('example.ipynb', as_version=4)

  executor.submit(exporter.from_notebook_node, nb).result()
```
```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 205, in _sendback_result
    exception=exception))
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 358, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'TemplateExporter._init_resources.<locals>.deprecated'
"""

The above exception was the direct cause of the following exception:    

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    executor.submit(exporter.from_notebook_node, nb).result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: Can't pickle local object 'TemplateExporter._init_resources.<locals>.deprecated'
```

**Nbconvert version: 6.0.0**

**Comment by MSeal** [comment]
Hmm can you list the full chain of dependencies you have? I'm not sure what change would have caused pickling to be angry at the init_resources traitlet. I can dig into this regardless but having the jupyter library versions you are using will help.

**Comment by kycutler** [comment]
@MSeal It was caused by a nested function defined in nbconvert -- I opened PR #1399 to fix it
