### ISSUE TITLE
KeyError: 'template_paths' when trying to download as HTML from within jupyter notebook

### ISSUE THREAD

**Issue by nfgrep** [jupyter/nbconvert#1437]
jupyter notebook throws an internal 500 error when trying to download as HTML.
I'm not familiar with the nbconvert or jupyter codebase so there's a high likelihood there's some error on my part, any help is appreciated.

Full Error:
```
Uncaught exception GET /nbconvert/html/1_assig.ipynb?download=true (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/nbconvert/html/1_assig.ipynb?download=true', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/traitlets/traitlets.py", line 535, in get
        value = obj._trait_values[self.name]
    KeyError: 'template_paths'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/notebook/nbconvert/handlers.py", line 93, in get
        exporter = get_exporter(format, config=self.config, log=self.log)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/notebook/nbconvert/handlers.py", line 67, in get_exporter
        Exporter = get_exporter(format)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
        super().__init__(config=config, **kw)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
        conf = self._get_conf()
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
        for path in map(Path, self.template_paths):
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/traitlets/traitlets.py", line 575, in __get__
        return self.get(obj, cls)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/traitlets/traitlets.py", line 538, in get
        default = obj.trait_defaults(self.name)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/traitlets/traitlets.py", line 1577, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/traitlets/traitlets.py", line 975, in __call__
        return self.func(*args, **kwargs)
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/templateexporter.py", line 518, in _template_paths
        template_names = self.get_template_names()
      File "/Users/nfg/Library/Python/3.8/lib/python/site-packages/nbconvert/exporters/templateexporter.py", line 601, in get_template_names
        raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
    ValueError: No template sub-directory with name 'lab' found in the following paths:
    	/Users/nfg/Library/Jupyter
    	/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/share/jupyter
    	/usr/local/share/jupyter
    	/usr/share/jupyter
[E 14:17:49.416 NotebookApp] {
      "Host": "localhost:8888",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1601835464|23:username-localhost-8888|44:ZDNmNzBjNjEzYTdjNDRiNDk3OWE0ODZkODllMTU4N2U=|a9e75b11ada6995ac92e274e628dd48e8665735dbf6a9c10822939c9e6c0ee73\"; _xsrf=2|c864399e|3b1740e5ef20710abe314a20113018a2|1600454282",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15",
      "Referer": "http://localhost:8888/notebooks/1_assig.ipynb",
      "Accept-Language": "en-ca",
      "Accept-Encoding": "gzip, deflate"
    }
[E 14:17:49.416 NotebookApp] 500 GET /nbconvert/html/1_assig.ipynb?download=true (::1) 31.59ms referer=http://localhost:8888/notebooks/1_assig.ipynb

```

**Nbconvert version:**
6.0.7

jupyter --version:
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.4
```

Tried:
- uninstalling/installing nbconvert
- pip upgrading both nbconvert and nbformat
- installing pandoc

**Comment by MSeal** [comment]
What's the command you are running?

This paths it searched in looks like the available template paths have been set / restricted:

>    	/Users/nfg/Library/Jupyter
>    	/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/share/jupyter
>   	/usr/local/share/jupyter
>   	/usr/share/jupyter

vs my (ubuntu) machine's paths:

> /home/mseal/.local/share/jupyter/nbconvert/templates/html
/home/mseal/.py3local/share/jupyter/nbconvert/templates/html
/usr/local/share/jupyter/nbconvert/templates/html
/usr/share/jupyter/nbconvert/templates/html
/home/mseal/Workspace/nbconvert/share/jupyter/nbconvert/templates/lab
/home/mseal/Workspace/nbconvert/share/jupyter/nbconvert/templates/base
/home/mseal/Workspace/nbconvert/share/jupyter
/home/mseal/Workspace/nbconvert/share/jupyter/nbconvert/templates
/home/mseal/Workspace/nbconvert/share/jupyter/nbconvert/templates/compatibility
/home/mseal/.local/share/jupyter
/home/mseal/.local/share/jupyter/nbconvert/templates
/home/mseal/.local/share/jupyter/nbconvert/templates/compatibility
/home/mseal/.py3local/share/jupyter
/home/mseal/.py3local/share/jupyter/nbconvert/templates
/home/mseal/.py3local/share/jupyter/nbconvert/templates/compatibility
/usr/local/share/jupyter
/usr/local/share/jupyter/nbconvert/templates
/usr/local/share/jupyter/nbconvert/templates/compatibility
/usr/share/jupyter
/usr/share/jupyter/nbconvert/templates
/usr/share/jupyter/nbconvert/templates/compatibility

specifically a `nbconvert/templates` path should be present in one of those printed paths you have with the templates present there

**Comment by nfgrep** [comment]
Ahh that helped a lot thank you. Turns out there was some issues with pip installing notebook along with its dependencies in user mode, putting things in the wrong place:
```
pip3 install notebook
Defaulting to user installation because normal site-packages is not writeable
```
I used [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment) to make a virtualenv, reinstalled notebook there and everything worked.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nbconvert-6-0-7-yields-valueerror-for-all-to-values-other-than-notebook/8166/2

**Comment by ZhouJunyu9102** [comment]
pip uninstall nbconvert
pip install nbconvert==5.6.1
may fix this problem?
