### ISSUE TITLE
c.NbConvertApp.output_base fails with --to pdf

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#144]
```
$ jupyter nbconvert --to pdf Advance\ python.ipynb
[NbConvertApp] Converting notebook Advance python.ipynb to pdf
[NbConvertApp] Writing 57050 bytes to /var/folders/ld/jy0c_5d91rl_s3jqh74tmqn00000gn/T/tmp8d5rjhkg/notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', '/var/folders/ld/jy0c_5d91rl_s3jqh74tmqn00000gn/T/tmp8d5rjhkg/notebook.tex', '-output-directory=/var/folders/ld/jy0c_5d91rl_s3jqh74tmqn00000gn/T/tmp8d5rjhkg', '-aux-directory=/var/folders/ld/jy0c_5d91rl_s3jqh74tmqn00000gn/T/tmp8d5rjhkg']
Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda3/bin/jupyter-nbconvert", line 9, in <module>
    load_entry_point('nbconvert==4.1.0.dev0', 'console_scripts', 'jupyter-nbconvert')()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.4/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/bussonniermatthias/dev/traitlets/traitlets/config/application.py", line 579, in launch_instance
    app.start()
  File "/Users/bussonniermatthias/dev/nbconvert/nbconvert/nbconvertapp.py", line 289, in start
    self.convert_notebooks()
  File "/Users/bussonniermatthias/dev/nbconvert/nbconvert/nbconvertapp.py", line 412, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/bussonniermatthias/dev/nbconvert/nbconvert/nbconvertapp.py", line 383, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/Users/bussonniermatthias/dev/nbconvert/nbconvert/nbconvertapp.py", line 335, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/bussonniermatthias/dev/nbconvert/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/Users/bussonniermatthias/dev/nbconvert/nbconvert/exporters/pdf.py", line 142, in from_notebook_node
    raise RuntimeError("PDF creating failed")
RuntimeError: PDF creating failed
```

I suppose the pdf exporter read the wrong filename as we shell out to tex ?

**Comment by minrk** [comment]
I believe this is fixed by #140. Can you check?

**Comment by Carreau** [comment]
Doesn't seem to. I'll dig deeper.

**Comment by minrk** [comment]
I merged #140 and this seems to be working as expected. Can you provide a more complete example?

**Comment by Carreau** [comment]
Added on my todo list for today. 
I have a talk tomorrow, but will try to do it.

**Comment by Carreau** [comment]
Ok, I clean up everything, and it works. I was likely in a an env without realising it (note to myself, stop using fish in bash in xonsh in fish in bash in zsh).

```
$ jupyter nbconvert --to pdf 'Advance python.ipynb'

[NbConvertApp] Converting notebook Advance python.ipynb to pdf
[NbConvertApp] Writing 108158 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 167569 bytes to exported-base-from-config.pdf
```

**Comment by minrk** [comment]
@Carreau thanks for confirming! I'll release 4.1 today, then.
