### ISSUE TITLE
Upgrading from 6.0.6 --> 6.0.7 appears to break nbsphinx usage

### ISSUE THREAD

**Issue by SimonBiggs** [jupyter/nbconvert#1442]
I use `nbsphinx` to use Notebooks within my documentation. For example:
https://docs.pymedphys.com/howto/gamma/effect-of-noise.html

When I upgrade 6.0.6 --> 6.0.7 I am now getting the following error message:

```
Notebook error:
TemplateNotFound in howto/gamma/effect-of-noise.ipynb:
rst.tpl
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/pymedphys/pymedphys/pymedphys/cli/__init__.py", line 146, in pymedphys_cli
    args.func(args)
  File "/home/runner/work/pymedphys/pymedphys/pymedphys/_dev/docs.py", line 22, in build_docs
    shell=True,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'poetry run sphinx-build -W /home/runner/work/pymedphys/pymedphys/docs /home/runner/work/pymedphys/pymedphys/docs/_build/html' returned non-zero exit status 2.
```

See https://github.com/pymedphys/pymedphys/runs/1224843568?check_suite_focus=true#step:31:28

The only difference between master and that branch is that the nbconvert pinning to 6.0.6 was removed:
https://github.com/pymedphys/pymedphys/pull/1087/files#r501560031

The notebook in question can be found at:
https://github.com/pymedphys/pymedphys/blob/master/docs/howto/gamma/effect-of-noise.ipynb

**Nbconvert version:**

**Comment by MSeal** [comment]
The `rst.tpl` filename was removed in 6.0.7. It was deprecated but we had to remove it earlier to fix a larger issue. The fix is to reference the `rst` template instead of the old file name, or if extending the rsp template inside jinja to extend `index.rst.j2` and set the base template in your conf.json to be `rst`. See https://nbconvert.readthedocs.io/en/latest/customizing.html

**Comment by mgeier** [comment]
This has been fixed some time ago (but apparently not permanently) by @takluyver in https://github.com/spatialaudio/nbsphinx/pull/344.
Since then, `rst.tpl` isn't used in `nbsphinx` anymore. Instead, `nbconvert.RSTExporter().template_file` is used.
But it looks like this is somehow broken now ...

**Comment by MSeal** [comment]
That's odd since that code should be picking up the correct filename...

```
In [1]: import nbconvert

In [2]: nbconvert.RSTExporter().template_file
Out[2]: 'index.rst.j2'
```

Do you have any custom config that references `rst.tpl`?

**Comment by mgeier** [comment]
@SimonBiggs Any news?

**Comment by SimonBiggs** [comment]
No usage of `rst.tpl`. See https://github.com/pymedphys/pymedphys/tree/master/docs for the docs build directory being used.

I am doing the following:
https://github.com/pymedphys/pymedphys/blob/47a5c3517b5e3240cf55db3f6bffa1ec7307631a/docs/conf.py#L109-L125

Might that be an issue?

**Comment by SnarkBoojum** [comment]
The docs/source/changelog.rst still references rst.tpl, so there's something amiss.
