### ISSUE TITLE
Problem in Converting Jupyter notebook to pdf

### ISSUE THREAD

**Issue by Japrap** [jupyter/nbconvert#1466]
When I want to save Jupyter notebook as a pdf file, I receive the following error:

```
nbconvert failed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex
? 
! Emergency stop.
<*> .\notebook
              .tex
No pages of output.
Transcript written on ?.
```
Any idea how can I solve this problem?

**Comment by SrinivasanShanmugam1311** [comment]
Dear Friends,

I am seeing this, while using nbconvert to pdf, any inputs or pointers onto this please, would be highly appreciated

C:\Users\user\anaconda3\Scripts>jupyter.exe nbconvert --to webpdf --WebPDFExporter.disable_sandbox=True C:\Users\user\Downloads\MDP_introduction.ipynb
Traceback (most recent call last):
File "", line 198, in run_module_as_main
File "", line 88, in run_code
File "C:\Users\user\anaconda3\Scripts\jupyter-nbconvert.EXE_main.py", line 4, in
File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\nbconvertapp.py", line 193, in
class NbConvertApp(JupyterApp):
File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\nbconvertapp.py", line 252, in NbConvertApp
Options include {get_export_names()}.
^^^^^^^^^^^^^^^^^^
File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\exporters\base.py", line 145, in get_export_names
e = get_exporter(exporter_name)(config=config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\exporters\base.py", line 106, in get_exporter
exporter = items[0].load()
^^^^^^^^^^^^^^^
File "C:\Users\user\anaconda3\Lib\importlib\metadata_init.py", line 202, in load
module = import_module(match.group('module'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\anaconda3\Lib\importlib_init_.py", line 126, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support_init.py", line 5, in
from .collapsible_headings import ExporterCollapsibleHeadings
File "C:\Users\user\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support\collapsible_headings.py", line 6, in
from notebook.services.config import ConfigManager
ModuleNotFoundError: No module named 'notebook.services'

C:\Users\user\anaconda3\Scripts>
Many thanks in advance,

**Comment by SrinivasanShanmugam1311** [comment]
And also another issue please, when I tried to install "pyppeteer-install" in anconda power shell prompt, I am seeing the below please : https://stackoverflow.com/questions/66514334/nbconvert-use-allow-chromium-download, any advises onto this also would be highly appreciated, many thanks in advance once again

(base) PS C:\Users\user> pyppeteer-install
[INFO] Starting Chromium download.
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\Users\user\anaconda3\Scripts\pyppeteer-install.exe_main.py", line 7, in
File "C:\Users\user\anaconda3\Lib\site-packages\pyppeteer\command.py", line 14, in install
download_chromium()
File "C:\Users\user\anaconda3\Lib\site-packages\pyppeteer\chromium_downloader.py", line 138, in download_chromium
extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\anaconda3\Lib\site-packages\pyppeteer\chromium_downloader.py", line 82, in download_zip
raise OSError(f'Chromium downloadable not found at {url}: ' f'Received {r.data.decode()}.\n')
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received NoSuchKeyThe specified key does not exist.

Details
No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip.
(base) PS C:\Users\user>
