### ISSUE TITLE
What is the official way for handling "--no-sandbox" situation?

### ISSUE THREAD

**Issue by ghuname** [jupyter/nbconvert#1490]
I get an error if I execute:

```
(base) jovyan@7876407ed131:~$ jupyter nbconvert --to webpdf bg_gradient.ipynb 
[NbConvertApp] Converting notebook bg_gradient.ipynb to webpdf

[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 93, in from_notebook_node
    pdf_data = self.run_pyppeteer(html)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 83, in run_pyppeteer
    pdf_data = pool.submit(run_coroutine, main()).result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 82, in run_coroutine
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 42, in main
    browser = await self._check_launch_reqs()(
  File "/opt/conda/lib/python3.8/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/opt/conda/lib/python3.8/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/opt/conda/lib/python3.8/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

(base) jovyan@7876407ed131:~$ 

```

After checking what is going on I have figured out that the problem is with "--no--sandbox" chromium option.
For example if I edit (in my case) `/opt/conda/lib/python3.8/site-packages/pyppeteer/launcher.py` and add last argument `--no-sandbox`:

```
DEFAULT_ARGS = [
    '--disable-background-networking',
    '--disable-background-timer-throttling',
    '--disable-breakpad',
    '--disable-browser-side-navigation',
    '--disable-client-side-phishing-detection',
    '--disable-default-apps',
    '--disable-dev-shm-usage',
    '--disable-extensions',
    '--disable-features=site-per-process',
    '--disable-hang-monitor',
    '--disable-popup-blocking',
    '--disable-prompt-on-repost',
    '--disable-sync',
    '--disable-translate',
    '--metrics-recording-only',
    '--no-first-run',
    '--safebrowsing-disable-auto-update',
    '--enable-automation',
    '--password-store=basic',
    '--use-mock-keychain',
    '--no-sandbox'
]
```
everything works. As @Mattwmaster58 suggested on https://github.com/pyppeteer/pyppeteer/issues/194#issuecomment-744588473, there are few options documented on https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox.

What is the official way for handling `--no-sandbox` situation?

**Nbconvert version:**
(base) jovyan@7876407ed131:~$ jupyter nbconvert --version
6.0.7

**Comment by Mattwmaster58** [comment]
The "official" way of dealing with it is exactly as documented in that link above - puppeteer DOES provide an interface for passing in arbitrary arguments, however, so editing the Lib files directly isn't necessary.

**Comment by ghuname** [comment]
@Mattwmaster58 
The problem I am facing with is that I am using `nbconvert --to webpdf` option, so I am using `pyppeteer` indirectly and I don't have a way to provide `--no-sandbox` parameter.

Maybe I am missing something. If you know how to execute `jupyter nbconvert --to webpdf bg_gradient.ipynb` and at the same time send `--no-sandbox`  to `pyppeteer`, please share.

Actually, I am looking for a way to avoid sanboxing because I don't know how to use it properly.
On https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox there are two explanations but I am not sure how to use them with nbconvert.

If you have an idea, I am listening very carefully.

**Comment by Mattwmaster58** [comment]
From a cursory look at the repo, it seems everything opened in the browser will already be completely trusted - therefore the avoidance of `--no-sandbox` is necessary IMO. One solution would be to submit a PR that allows a CLI flag to be used to pass `--no-sandbox` to `pyppeteer.launch`

**Comment by ghuname** [comment]
So you are suggesting that nbconvert should have a new flag (name unknown) that will be used to pass `--no-sandbox` to `pyppeteer.launch`.
Please do confirm to avoid necessary confusion.

**Comment by Mattwmaster58** [comment]
Yep, exactly that.

**Comment by zljubisic** [comment]
@Mattwmaster58 Well, as I don't have a  write permissions I cannot create pull request.

**Comment by Mattwmaster58** [comment]
Yeah, you'll rarely have write permissions for a given repo, so int this case you'll need to _fork_ the repo first, make the changes in your (copied) repo, then come back to this repo and make a pull request.
