### ISSUE TITLE
Custom Exporter

### ISSUE THREAD

**Issue by ugogon** [jupyter/nbconvert#1492]
I implemented the example custom exporter like described here: [https://nbconvert.readthedocs.io/en/latest/external_exporters.html](https://nbconvert.readthedocs.io/en/latest/external_exporters.html).

It throws me the following error:

```
$ jupyter nbconvert --to jupyterconverter.MyExporter notebook.ipynb                                                              
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxx/anaconda3/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 140, in <module>
    class NbConvertApp(JupyterApp):
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 225, in NbConvertApp
    """.format(formats=get_export_names()))
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
    if getattr(exporter(config=config), 'enabled', True):
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
    super().__init__(config=config, **kw)
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
    conf = self._get_conf()
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
    for path in map(Path, self.template_paths):
  File "/media/xxxx/Data/Projekte/JupyterConverter/jupyterconverter/__init__.py", line 94, in template_paths
    return super().template_paths + [os.path.join(os.path.dirname(__file__), "templates")]
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/home/xxxx/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 1574, in trait_defaults
    "instances" % (n, type(self).__name__))
traitlets.traitlets.TraitError: 'template_paths' is not a trait of 'MyExporter' instances
```

Is it my fault or did the API change?

```
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 5.0.1
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.4
```

Thanks!

**Comment by asirjoosingh** [comment]
I have the same problem using the example from the docs. I've tried going back to previous 6.x versions with the same error.

Any help on this would be greatly appreciated!

**Comment by HeinrichHartmann** [comment]
This issue seems to be caused by interplay of super() with traitlets. 

```
 # File "/media/xxxx/Data/Projekte/JupyterConverter/jupyterconverter/__init__.py", line 94, in template_paths
return super().template_paths + [os.path.join(os.path.dirname(__file__), "templates")]
```

This statement, should be returning the teamplate_paths of the underlying TemplateExplorer object but fails to do so:
```
super().template_paths
```

Bandaid: Change the line in the example to:
```
return super()._template_paths() + [os.path.join(os.path.dirname(__file__), "templates")]
```

This changes the semantics and uses undocumented features, as `_template_paths()` computes default value for .template_paths. But it got this poblem a proper fix is found.

**Comment by asirjoosingh** [comment]
Thank you for the bandaid/fix suggestion. Glad to have help for a workaround for this issue. Appreciate the reply!

**Comment by bsyouness** [comment]
Was running into the same issue, thanks @HeinrichHartmann for the fix!
