### ISSUE TITLE
Template directories not created with world-readable permissions

### ISSUE THREAD

**Issue by colinasmith** [jupyter/nbconvert#1559]
I'm using Jypyter notebooks in a multi-user environment, with the anaconda distribution maintained by a non-root user (**user A**). When **user A** first uses a Jupyter notebook, a new `share/jupyter/nbconvert/templates/html` directory is created that is only readable by that user. That causes subsequent use by another user (**user B**) to fail. The suggested fixes are either/both:

1. When subdirectories are created in `share/jupyter/nbconvert/templates`, make sure they're world readable (i.e. `go+rx`)
2. When a permissions denied error is encountered when reading `nbconvert` settings, don't throw an uncaught exception, especially when user-specific settings can be accessed in the home directory.

This issue appears related to several other issues (#1167 and #1430). In issue #1167, MSeal appears to disfavor suggested fix 2. However, given that the permissions issue appears to be created by `nbconvert` itself, I think `nbconvert` should be more forgiving. I think there is no reason not to implement fix 1.

Steps to reproduce:
1. Install latest version of anaconda as **user A**
2. `conda create -n r_jupyter`
3. `conda activate r_jupyter`
4. `conda install r-recommended r-irkernel Jupyter`
5. Run `ls -la` in `share/jupyter/nbconvert/templates`:
```
drwxr-xr-x. 14 csmith06 smithlab 4096 Apr 22 10:27 .
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 ..
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 asciidoc
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 base
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 basic
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 classic
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 compatibility
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 lab
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 latex
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 markdown
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 python
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 reveal
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 rst
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 script
```
6. Run jupyter as **user B** and then open a notebook: `jupyter-notebook --no-browser` (**This is successful!**)
7. Run jupyter as **user A** and then open a notebook: `jupyter-notebook --no-browser`
8. Run `ls -la` in share/jupyter/nbconvert/templates (note new html directory with permissions 700):
```
drwxr-xr-x. 15 csmith06 smithlab 4096 Apr 29 09:49 .
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 ..
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 asciidoc
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 base
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 basic
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 classic
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 compatibility
drwx------.  2 csmith06 smithlab 4096 Apr 29 09:49 html
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 lab
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 latex
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 markdown
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 python
drwxr-xr-x.  3 csmith06 smithlab 4096 Apr 22 10:27 reveal
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 rst
drwxr-xr-x.  2 csmith06 smithlab 4096 Apr 22 10:27 script
```
9. Run jupyter as **user B** and then open a notebook: `jupyter-notebook --no-browser` Upon opening the notebook, a **500 : Internal Server Error** is encountered in the web browser. The following error is printed to the console:
```
[E 09:50:24.967 NotebookApp] Uncaught exception GET /notebooks/remd/equil/potential_energies.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/notebooks/remd/equil/potential_energies.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/notebook/templates/notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
        for name in get_export_names():
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
        super().__init__(config=config, **kw)
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
        conf = self._get_conf()
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 509, in _get_conf
        if conf_path.exists():
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/pathlib.py", line 1407, in exists
        self.stat()
      File "/lab/anaconda/envs/r_jupyter/lib/python3.9/pathlib.py", line 1221, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/lab/anaconda/envs/r_jupyter/share/jupyter/nbconvert/templates/html/conf.json'
```

```
jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : 5.0.3
ipython          : 7.22.0
ipykernel        : 5.3.4
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

**Comment by feinsteinben** [comment]
We also encountered this issue.

**Comment by casparvl** [comment]
+1. Is there any reason why the `umask` of the particular system is not just used? We have a Python environment that is readable to a certain Unix group, but the templates are the only part that cause trouble because they don't respect the `umask` when being installed.
