### ISSUE TITLE
nbconvert issue with installing templates: `jinja2.exceptions.TemplateNotFound: classic`

### ISSUE THREAD

**Issue by connorferster** [jupyter/nbconvert#1579]
There seems to be an issue with installing custom templates. Taking @SylvainCorlay's example at https://github.com/SylvainCorlay/nbconvert-acme/, I can install the template successfully. However, when I try to use it, I hit an error that I have seen before trying to create my own custom templates last week (see #1574). Because I was running into this error previously, I assumed it was a problem with my exporter and template. However, today I tried to install the **acme** minimal example template and I am running into the same error.

Could this be an issue with both the **acme** template and my template? Yes, possibly. However, I also visually checked the `acme-venv/share/jupyter/nbconvert/templates` directory and I see all of the nbconvert templates (including `classic`) in addition to the `acme` template. I then also ran the following command using one of the built-in nbconvert templates and encountered the same error:

```
 python -m nbconvert --template html --to html notebooks/acme.ipynb
```

This leads me to believe that the issue is actually with nbconvert.

Is this the case or am I missing something about how to use nbconvert properly? Many thanks to anyone who is able to look at this issue.

## Steps to reproduce

(I am using Git bash on Windows 10)
```
python -m venv acme-venv
source acme-venv/Scripts/activate
pip install nbconvert
pip install git+https://github.com/SylvainCorlay/nbconvert-acme.git
python -m nbconvert --template acme --to html notebooks/acme.ipynb
```

This causes the following error:

```python
[NbConvertApp] Converting notebook notebooks/acme.ipynb to html
Traceback (most recent call last):
  File "C:\Users\cferster\Anaconda3\lib\runpy.py", line 193, in _run_module_as_m
ain
    "__main__", mod_spec)
  File "C:\Users\cferster\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\__main__.py", line 2, in <module>
    main()
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\traitlets\config\application.py", line 845, in launch_instanc
e
    app.start()
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\nbconvertapp.py", line 489, in convert_single_noteb
ook
    output, resources = self.export_single_notebook(notebook_filename, resources
, input_buffer=input_buffer)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\nbconvertapp.py", line 418, in export_single_notebo
ok
    output, resources = self.exporter.from_filename(notebook_filename, resources
=resources)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\exporters\exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), res
ources=resources, **kw)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\exporters\html.py", line 119, in from_notebook_node

    return super().from_notebook_node(nb, resources, **kw)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\exporters\templateexporter.py", line 384, in from_n
otebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\exporters\templateexporter.py", line 148, in templa
te
    self._template_cached = self._load_template()
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\nbconvert\exporters\templateexporter.py", line 355, in _load_
template
    return self.environment.get_template(template_file)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\cferster\Notebooks\package_development\nbconvert-acme\venv-acme
\lib\site-packages\jinja2\loaders.py", line 556, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: classic
```

**Nbconvert version:**
```
python -m nbconvert --version
6.0.7
```

**Comment by SylvainCorlay** [comment]
Hey, I am essentially off the grid or a few days.

Quick remark: could this be an issue with the handling of virtual environments?

**Comment by connorferster** [comment]
Thank you for the quick response. That is certainly possible. It would be good to know if there is a better way to set up a virtual environment for developing/testing nbconvert templates. I can try setting up a new conda environment instead of a venv and see how that goes.

**Comment by connorferster** [comment]
Ok, I created a new conda environment and with only Jupyter Lab installed and received the same error.

### Steps to Reproduce
```
conda create --name nbconvert python=3.7
activate nbconvert
conda install jupyterlab
<navigate to a dir with a .ipynb file>
jupyter nbconvert --to html my_file.ipynb
```

See the error (variation on a theme) below:

```python
(nbconvert) C:\Users\cferster\Notebooks\Calcs\Wood\Glulam>jupyter nbconvert --to html "Beam Vibration.ipynb"
[NbConvertApp] Converting notebook Beam Vibration.ipynb to html
Traceback (most recent call last):
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\exporters\exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\exporters\html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\exporters\templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\exporters\templateexporter.py", line 148, in template
    self._template_cached = self._load_template()
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\nbconvert\exporters\templateexporter.py", line 355, in _load_template
    return self.environment.get_template(template_file)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\jinja2\environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\jinja2\environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\cferster\Anaconda3\envs\nbconvert\lib\site-packages\jinja2\loaders.py", line 556, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: classic
```

**Comment by connorferster** [comment]
Is anyone able to reproduce this?

**Comment by MSeal** [comment]
I'm not able to reproduce this issue.

Try removing checking your jupyter paths for older installed template:

```
$ jupyter --paths
config:
    /home/mseal/.jupyter
    /home/mseal/.py3local/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/mseal/.local/share/jupyter
    /home/mseal/.py3local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/mseal/.local/share/jupyter/runtime
```

Perhaps you have some user profile path that didn't get cleaned up with 5.6.1 template files referencing `classic`. You can search for the `lab` tempalates therein and make sure they have a `conf.json` with a `"base_template": "base",` entry. Or just nuke all references to nbconvert in your jupyter paths and reinstall to reset them. Furthermore make sure you're not in the working directory of nbconvert checked out to 5.6.1 (unlikely but could cause it?).
