### ISSUE TITLE
PDF creating fails with matrix

### ISSUE THREAD

**Issue by kennysong** [jupyter/nbconvert#158]
If I make an empty notebook with this line, exporting as PDF fails with a server error:

```
$$
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 2 & 6t_3 & 0 & 0 & -2
\end{pmatrix}
$$
```

Interestingly, this line (with the last element removed) exports correctly.

```
$$
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 2 & 6t_3 & 0 & 0
\end{pmatrix}
$$
```

Here is the server error log, 

```
[I 11:16:31.590 NotebookApp] Building PDF
[I 11:16:31.591 NotebookApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[C 11:16:32.073 NotebookApp] pdflatex failed: ['pdflatex', 'notebook.tex']
    This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
     restricted \write18 enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2015/01/01>
    Babel <3.9l> and hyphenation patterns for 79 languages loaded.
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/size10.clo))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/graphics.cfg)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/pdftex-def/pdftex.def
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/adjustbox.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/xkeyval/xkeyval.tex
    (/usr/local/texlive/2015/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/trimclip.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/collectbox/collectbox.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/varwidth/varwidth.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/color.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/color.cfg))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/tools/enumerate.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amstext.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsgen.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsbsy.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsopn.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amssymb.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/eurosym/eurosym.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/ucs.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/data/uni-global.def))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/inputenc.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/utf8x.def))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix
    <2008/02/07> (tvz))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/grffile.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/etexcmds.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/auxhook.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/pd1enc.def)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/url/url.sty))

    Package hyperref Message: Driver (autodetected): hpdftex.

    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hpdftex.def
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/tools/longtable.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/booktabs/booktabs.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/ulem/ulem.sty)
    No file notebook.aux.
    (/usr/local/texlive/2015/texmf-dist/tex/context/base/supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    ) (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/grfext.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex

    Package geometry Warning: The marginal notes overrun the paper.
         Add 3.73001pt and more to the right margin.

    *geometry* verbose mode - [ preamble ] result:
    * driver: pdftex
    * paper: <default>
    * layout: <same size as paper>
    * layoutoffset:(h,v)=(0.0pt,0.0pt)
    * modes:
    * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
    * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
    * \paperwidth=614.295pt
    * \paperheight=794.96999pt
    * \textwidth=469.75502pt
    * \textheight=650.43001pt
    * \oddsidemargin=0.0pt
    * \evensidemargin=0.0pt
    * \topmargin=-37.0pt
    * \headheight=12.0pt
    * \headsep=25.0pt
    * \topskip=10.0pt
    * \footskip=30.0pt
    * \marginparwidth=65.0pt
    * \marginparsep=11.0pt
    * \columnsep=10.0pt
    * \skip\footins=9.0pt plus 4.0pt minus 2.0pt
    * \hoffset=0.0pt
    * \voffset=0.0pt
    * \mag=1000
    * \@twocolumnfalse
    * \@twosidefalse
    * \@mparswitchfalse
    * \@reversemarginfalse
    * (1in=72.27pt=25.4mm, 1cm=28.453pt)

    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/ucsencs.def)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/umsa.fd)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/umsb.fd)

    LaTeX Warning: No \author given.

    ! Extra alignment tab has been changed to \cr.
    <recently read> \endtemplate

    l.252 0 & 0 & 0 & 0 & 0 & 0 & 2 & 6t_3 & 0 & 0 &
                                                     -2
    ?
    ! Emergency stop.
    <recently read> \endtemplate

    l.252 0 & 0 & 0 & 0 & 0 & 0 & 2 & 6t_3 & 0 & 0 &
                                                     -2
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.

[I 11:16:32.076 NotebookApp] Running bibtex 1 time: ['bibtex', 'notebook']
[W 11:16:32.224 NotebookApp] bibtex had problems, most likely because there were no citations
[I 11:16:32.227 NotebookApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[C 11:16:32.682 NotebookApp] pdflatex failed: ['pdflatex', 'notebook.tex']
    This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
     restricted \write18 enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2015/01/01>
    Babel <3.9l> and hyphenation patterns for 79 languages loaded.
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/size10.clo))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/graphics.cfg)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/pdftex-def/pdftex.def
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/adjustbox.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/xkeyval/xkeyval.tex
    (/usr/local/texlive/2015/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/trimclip.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/collectbox/collectbox.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/varwidth/varwidth.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/color.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/color.cfg))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/tools/enumerate.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amstext.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsgen.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsbsy.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsopn.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amssymb.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/eurosym/eurosym.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/ucs.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/data/uni-global.def))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/inputenc.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/utf8x.def))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix
    <2008/02/07> (tvz))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/grffile.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/etexcmds.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/auxhook.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/pd1enc.def)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/url/url.sty))

    Package hyperref Message: Driver (autodetected): hpdftex.

    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hpdftex.def
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
    (/usr/local/texlive/2015/texmf-dist/tex/latex/tools/longtable.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/booktabs/booktabs.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/generic/ulem/ulem.sty) (./notebook.aux)
    (/usr/local/texlive/2015/texmf-dist/tex/context/base/supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    ) (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
    (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/grfext.sty)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex

    Package geometry Warning: The marginal notes overrun the paper.
         Add 3.73001pt and more to the right margin.

    *geometry* verbose mode - [ preamble ] result:
    * driver: pdftex
    * paper: <default>
    * layout: <same size as paper>
    * layoutoffset:(h,v)=(0.0pt,0.0pt)
    * modes:
    * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
    * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
    * \paperwidth=614.295pt
    * \paperheight=794.96999pt
    * \textwidth=469.75502pt
    * \textheight=650.43001pt
    * \oddsidemargin=0.0pt
    * \evensidemargin=0.0pt
    * \topmargin=-37.0pt
    * \headheight=12.0pt
    * \headsep=25.0pt
    * \topskip=10.0pt
    * \footskip=30.0pt
    * \marginparwidth=65.0pt
    * \marginparsep=11.0pt
    * \columnsep=10.0pt
    * \skip\footins=9.0pt plus 4.0pt minus 2.0pt
    * \hoffset=0.0pt
    * \voffset=0.0pt
    * \mag=1000
    * \@twocolumnfalse
    * \@twosidefalse
    * \@mparswitchfalse
    * \@reversemarginfalse
    * (1in=72.27pt=25.4mm, 1cm=28.453pt)

    (/usr/local/texlive/2015/texmf-dist/tex/latex/ucs/ucsencs.def)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty
    (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
    (./notebook.out) (./notebook.out)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/umsa.fd)
    (/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/umsb.fd)

    LaTeX Warning: No \author given.

    ! Extra alignment tab has been changed to \cr.
    <recently read> \endtemplate

    l.252 0 & 0 & 0 & 0 & 0 & 0 & 2 & 6t_3 & 0 & 0 &
                                                     -2
    ?
    ! Emergency stop.
    <recently read> \endtemplate

    l.252 0 & 0 & 0 & 0 & 0 & 0 & 2 & 6t_3 & 0 & 0 &
                                                     -2
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.

[W 11:16:32.684 NotebookApp] 500 GET /nbconvert/pdf/Dropbox/NYUSH/Junior%20Year/Numerical%20Methods/Untitled.ipynb?download=true (::1): nbconvert failed: PDF creating failed
[E 11:16:32.688 NotebookApp] Exception in exception handler
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/notebook/nbconvert/handlers.py", line 102, in get
        "config_dir": self.application.settings['config_dir'],
      File "/usr/local/lib/python3.5/site-packages/nbconvert/exporters/pdf.py", line 152, in from_notebook_node
        raise IOError("PDF creating failed")
    OSError: PDF creating failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 2800, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/site-packages/notebook/nbconvert/handlers.py", line 106, in get
        raise web.HTTPError(500, "nbconvert failed: %s" % e)
    tornado.web.HTTPError: HTTP 500: Internal Server Error (nbconvert failed: PDF creating failed)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1450, in _execute
        self._handle_request_exception(e)
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1502, in _handle_request_exception
        self.send_error(e.status_code, exc_info=sys.exc_info())
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 978, in send_error
        self.finish()
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/usr/local/lib/python3.5/site-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 201, in encode
        chunks = list(chunks)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 436, in _iterencode
        o = _default(o)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x103726588> is not JSON serializable
```

**Comment by juhasch** [comment]
This is a TeX issue.
```
The maximum number of columns in a matrix is determined by the counter MaxMatrixCols
 (normal value = 10), which you can change if necessary using \setcounter or 
\addtocounter commands.
```
See: http://tex.stackexchange.com/questions/95162/how-to-create-a-matrix-with-20-columns-in-latex

You need to add `\setcounter{MaxMatrixCols}{20}` to the Latex template or create your own.

**Comment by takluyver** [comment]
Thanks @juhasch .
