### ISSUE TITLE
How to select the LaTeX template?

### ISSUE THREAD

**Issue by cholmcc** [jupyter/nbconvert#1671]
Hi, 

I have a little trouble figuring out how to specify the template to use when converting to LaTeX.    If one does 

    jupyter nbconvet --to latex Test.ipynb 

one will use the default template **latex** from `share/jupyter/nbconvert/templates/latex/index.tex.j2`.  But suppose I'd rather use the **report** document class - then, naively I would think to do 

    jupyter nbconvet --to latex --template report Test.ipynb 
 
(that's how it worked in _nbconvert_ < 6.0) which would presumably read `share/jupyter/nbconvert/templates/latex/report.tex.j2`.  However, that does not work.  The (shortened) stack trace is 

```
$ jupyter  nbconvert --to latex --template report Test.ipynb 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 33, in <module>
    sys.exit(load_entry_point('nbconvert==6.1.0', 'console_scripts', 'jupyter-nbconvert')())
...
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/templateexporter.py", line 526, in _template_paths
    template_names = self.get_template_names()
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/templateexporter.py", line 609, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'report' found in the following paths:
	/home/user/.local/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter
```

I also tried specifying the template as 

- `latex/report` 
- `latex.report` 

with similar results.  However, specifying the template file name with `--template-file` seems to work 

    jupyter nbconvert --to latex --template latex --template-file report.tex.j2 Test.ipynb 
    jupyter nbconvert --to latex --template-file report.tex.j2 Test.ipynb 

Is this how it is intended to work?  The documentation (both via option `--help` and the [web-pages](https://nbconvert.readthedocs.io/en/latest/index.html)) provides no hints of this.   Similarly, the documentation provides no information on setting the cell-style template 

    jupyter nbconvert --to latex  --template-file report.tex.j2 --LatexExporter.cell_style=style_bw_python.tex.js Test.ipynb

which would also be useful to make it more evident.

Yours, 

Christian

as well as 

    jupyter  nbconvert --to latex --template-file /usr/share/jupyter/nbconvert/templates/latex/report.tex.j2 Test.ipynb 

all with the same result.

**Comment by MSeal** [comment]
Hi cholmcc,

The intention is that "Use --template-name for the template directory with a index.<ext>.j2 file and/or --template-file to denote a different template." This should be a warning message sent when you use `template_name` in the 5.x style, but our documentation could use improvements around this. The old `template` flag maps to `template-name` for convenience, though it add a little confusion by not raising an exception.

https://nbconvert.readthedocs.io/en/latest/customizing.html specifically needs to reference the difference in the two field names if someone has a cycle to help improve that.

**Comment by cholmcc** [comment]
I'm not sure I understand you reply.  The argument `--template <name>` selects a directory - say `some/path/<name>` - with an `index.<mime>.j2` file in it. If nothing else is done then that `some/path/<name>/index<mime>.j2` file is taken to be the template to use.  

If the user specifies `--template-name <sub>` then it is assumed to name a file in `some/path/<name>` minus the ending ` .<mime>.j2`.  That is, the file `some/path/<name>/<sub>.<mime>.j2` is used as the template. 

If the user specifies `--template-file <filename>` and this does not name a legacy template, then it seems that nbconvert will read `some/path/<name>/<filename>` as the template. 

I can see why `--template-file` is discouraged, but `--template-name` seems to be exactly what you want.  It may be slightly misnamed, and one could think of other ways of specifying a "sub" template f.ex. 

    --template <name>#<sub> 
    --template file:/<path-to>/<name>#<sub> 
    --template https://<host>/<path-to>/<name>#sub 

and even expand that scheme with URL options - f.ex 

    --template latex?cell_style=style_bw_python#report

and so on.  

If you decide to update the documentation, please also consider to update the documentation of `TemplateExporter.extra_template_basedirs`, `TemplateExporter.extra_template_data_dir`, and so on.  A few examples, perhaps, would be beneficial.

**Comment by miccoli** [comment]
> https://nbconvert.readthedocs.io/en/latest/customizing.html specifically needs to reference the difference in the two field names if someone has a cycle to help improve that.

Let me point out another place in the docs that needs to be updated.

As of  ver. 7.0.0.rc3, <https://nbconvert.readthedocs.io/en/latest/usage.html#convert-latex> is wrong: the old option (`--template report`) instead of the new one (`--template-file report`) is documented.
