### ISSUE TITLE
Colab Browser closed unexpectedly

### ISSUE THREAD

**Issue by KamuiAkuto** [jupyter/nbconvert#1694]
So i have a small problem with converting to webpdf or pdfviahtml in Google Colab. If I try to convert to webpdf I get the Error: pyppeteer.errors.BrowserError: Browser closed unexpectedly. 
After some researching i got the suggestion to disable sandbox and/or install chrome drivers. Both did not help.
Does somebody know how to fix this or has experience with it in Google Colab

Code:
```
%%capture test
!pip install folium==0.2.1
#!pip install urllib3==1.24.3

!apt-get install texlive texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-plain-generic pandoc
!pip install pypandoc -U

!sudo apt-get update
!sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libcairo-gobject2 libxinerama1 libgtk2.0-0 libpangoft2-1.0-0 libthai0 libpixman-1-0 libxcb-render0 libharfbuzz0b libdatrie1 libgraphite2-3 libgbm1
```
Need to restart the runtime after this command
```
!pip install nbconvert --upgrade
```
```
%%capture test
!python -m pip install -U notebook-as-pdf
!pip install nbconvert[webpdf] -U
!pyppeteer-install
!sudo apt install chromium-chromedriver
```
```
!jupyter-nbconvert --to webpdf --disable-chromium-sandbox --WebPDFExporter.disable_sandbox=True /content/drive/MyDrive/Notebooks/ex09_04EeeeeeeM.ipynb
```
Ausgabe der letzten Zelle
```
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[NbConvertApp] Converting notebook /content/drive/MyDrive/Notebooks/ex09_04EeeeeeeM.ipynb to webpdf
[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 361, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 533, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 498, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 427, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/exporters/exporter.py", line 186, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/exporters/exporter.py", line 204, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/exporters/webpdf.py", line 149, in from_notebook_node
    pdf_data = self.run_pyppeteer(html)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/exporters/webpdf.py", line 136, in run_pyppeteer
    pdf_data = pool.submit(run_coroutine, main(temp_file)).result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/exporters/webpdf.py", line 135, in run_coroutine
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/exporters/webpdf.py", line 87, in main
    args=args
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```

Colab Notebook
https://colab.research.google.com/drive/1fpKK4AVQUjQmQUWqUPPWXCpBGF1Oc4oZ?usp=sharing

**Comment by KamuiAkuto** [comment]
Soooooo  i some how found a solution. I overwrite the launcher.py and change the executable to the one that the `!sudo apt install chromium-chromedriver` downloaded. 
Now the convert does not give the error anymore. 
But now i have the problem that the pdf does not include plotly graphs. (╯°□°)╯︵ ┻━┻

**Comment by KamuiAkuto** [comment]
soooo also fixed te ploty thing. the notebook to convert has to have the following code in it
```
import plotly.io as pio
pio.renderers.default='notebook'
```
