### ISSUE TITLE
"KeyError: 'state'" when trying to convert a notebook from Google Colab

### ISSUE THREAD

**Issue by mrdbourke** [jupyter/nbconvert#1731]
Hello,

I seem to every so often get the following error:

```
File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbconvert/filters/widgetsdatatypefilter.py", line 56, in __call__
[95](https://github.com/mrdbourke/pytorch-deep-learning/runs/5597148101?check_suite_focus=true#step:8:95)
    metadata['widgets'][WIDGET_STATE_MIMETYPE]['state'] if
[96](https://github.com/mrdbourke/pytorch-deep-learning/runs/5597148101?check_suite_focus=true#step:8:96)
KeyError: 'state'
[97](https://github.com/mrdbourke/pytorch-deep-learning/runs/5597148101?check_suite_focus=true#step:8:97)
Error: Process completed with exit code 1.
```

It seems to be most often when I'm saving a notebook from Google Colab into GitHub and then running a GitHub Action to convert it directly into documentation.

The GitHub Action traceback can be seen here: https://github.com/mrdbourke/pytorch-deep-learning/runs/5597148101?check_suite_focus=true 

The notebook in question can be found here: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/03_pytorch_computer_vision.ipynb

The issue doesn't occur on other notebooks converted in the same manner. 

Things I've tried:
* Make a copy of the notebook, resave under same name (in Google Colab)
* Clone the notebook locally, rerun, save, commit

Both of these result in the same result as above.

Any help would be greatly appreciated, I'm not quite sure where this error is coming from nor why it happens to some notebooks and not others.

To the best of my knowledge, the notebook it happens on "03_pytorch_computer_vision.ipynb" uses the exact same style as other notebooks (Python code and markdown).

**Comment by YIREN1** [comment]
seeing the same issue when saving using colab and then convert into html/pdf

**Comment by pplonski** [comment]
The same here! We are using `nbconvert` in our framework [Mercury](https://github.com/mljar/mercury) to add widgets to notebooks (to make notebooks as interactive web apps). What is more interesting the notebook is not using widgets at all!

Some workaround might be a removal of `metadata/widgets` from notebook JSON.

**Comment by scienception** [comment]
Same issue, did you manage to solve it?

**Comment by pplonski** [comment]
Remove `metadata/widgets` in notebook file.

**Comment by alimanfoo** [comment]
Just wondering if anyone has raised this with the colab devs? Looks like they need to update the way that widget state is stored in the notebook JSON.

**Comment by hs211216** [comment]
Just hit with https://colab.research.google.com/github/kstathou/vector_engine/blob/master/notebooks/001_vector_search.ipynb

The workaround recommended by **@pplonski** worked for me.  Here is what I did

1. Download 001_vector_search.ipynb with Colab gui
  
2. Fail to convert it with nbconvert
      
```
% jupyter nbconvert --to html 001_vector_search.ipynb
  [NbConvertApp] Converting notebook 001_vector_search.ipynb to html
  Traceback (most recent call last):
    File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
      return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
    ...
    File "/usr/local/share/jupyter/nbconvert/templates/base/display_priority.j2", line 7, in block 'data_priority'
      {%- for type in output.data | filter_data_type -%}
    File "/usr/local/lib/python3.9/site-packages/nbconvert/filters/widgetsdatatypefilter.py", line 57, in __call__
      metadata["widgets"][WIDGET_STATE_MIMETYPE]["state"]
  KeyError: 'state'
```

3. Remove .metadata.widgets with Jq
  
```
% jq -M 'del(.metadata.widgets)' 001_vector_search.ipynb > 001_vector_search.fixed.ipynb
% jupyter nbconvert --to html 001_vector_search.fixed.ipynb
  [NbConvertApp] Converting notebook 001_vector_search.fixed.ipynb to html
  [NbConvertApp] Writing 629781 bytes to 001_vector_search.fixed.html

% open 001_vector_search.fixed.ipynb

  ... output looks good
```


For reference I'm on OSX 10.15.7 and here are my jupyter versions
      
```
% jupyter --version
  Selected Jupyter core packages...
  IPython          : 8.0.1
  ipykernel        : 6.9.0
  ipywidgets       : not installed
  jupyter_client   : 7.1.2
  jupyter_core     : 4.9.1
  Jupyter_server   : not installed
  jupyterlab       : not installed
  nbclient         : 0.6.4
  nbconvert        : 6.5.0
  nbformat         : 5.4.0
  notebook         : not installed
  qtconsole        : not installed
  traitlets        : 5.2.2
```

**Comment by Pqlet** [comment]
> Remove `metadata/widgets` in notebook file.

Thanks

"Widgets" --> "Clear Notebook Widgets State" helped me in jupyter

**Comment by ndjhartman** [comment]
Dumb workout for without access to CLI jq and without reuploading to Colab:

1. Open .ipynb file in notepad
2. Copy file JSON contents
3. Go to https://jqplay.org/
4. Paste contents into `JSON` field
5. Paste `del(.metadata.widgets)` into filter pane (Thanks @hs211216)
6. Copy result from right pane
7. Paste into original .ipynb file
8. Save file and exit

Works now.

**Comment by jameswcoquat** [comment]
Clear Widget State at the top of the notebook FTW!

**Comment by Xu-Justin** [comment]
**Notes:** If you are unable to locate the Widget tab on your notebook, which happened to me as well, you will need to install `ipywidgets` by executing the following command and restart your notebook.
```bash
$ pip install ipywidgets

```

**Comment by tsoahii** [comment]
I first cleared the widgets section in the metadata fully (use e.g. Notepad as raw editor, the widget section is at the end of file):
"widgets": {}

Then ran and saved the notebook from a jupyter server, which I normally don't do because I edit and run from vscode.
After that the widget field looked like this:
"widgets": {
 "application/vnd.jupyter.widget-state+json": {
  "state": {},
  "version_major": 2,
  "version_minor": 0
 }
}

With this new notebook metadata, I was able to export without errors.

**Comment by mrdbourke** [comment]
> 

This helped me too!

**Note:** This requires a traditional notebook layout (e.g. Jupyter Notebook Classic).

See:

<img width="1392" alt="Screenshot 2023-08-25 at 4 36 51 pm" src="https://github.com/jupyter/nbconvert/assets/16750345/a7dec685-77f0-4169-8d15-119707bc1487">

**Comment by hlin863** [comment]
> > > Remove `metadata/widgets` in notebook file.
> > 
> > 
> > Thanks
> > "Widgets" --> "Clear Notebook Widgets State" helped me in jupyter
> 
> This helped me too!
> 
> --
> 
> **Note:** This requires a traditional notebook layout (e.g. Jupyter Notebook Classic).
> 
> See:
> 
> <img alt="Screenshot 2023-08-25 at 4 36 51 pm" width="1392" src="https://user-images.githubusercontent.com/16750345/263187057-a7dec685-77f0-4169-8d15-119707bc1487.png">

I don't see that option for clearing widget stats on my Google collab. Would you like to clarify how to get that tab?

**Comment by mrdbourke** [comment]
Hi @hlin863, as far as I know the option isn't available in Google Colab.

I accessed it via using the original Jupyter Notebook. 

For example, going to terminal and typing `jupyter notebook`.

**Comment by mrdbourke** [comment]
> > > Remove `metadata/widgets` in notebook file.
> > 
> > 
> > Thanks
> > "Widgets" --> "Clear Notebook Widgets State" helped me in jupyter
> 
> This helped me too!
> 
> --
> 
> **Note:** This requires a traditional notebook layout (e.g. Jupyter Notebook Classic).
> 
> See:
> 
> <img alt="Screenshot 2023-08-25 at 4 36 51 pm" width="1392" src="https://private-user-images.githubusercontent.com/16750345/263187057-a7dec685-77f0-4169-8d15-119707bc1487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTA3MDYsIm5iZiI6MTcwNjg1MDQwNiwicGF0aCI6Ii8xNjc1MDM0NS8yNjMxODcwNTctYTdkZWM2ODUtNzdmMC00MTY5LThkMTUtMTE5NzA3YmMxNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA1MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OTM2OWJkNThiZGM0ZDY0NGE2NmM0YTFiZTY1MDEwNWUzMjE5MDMxNDA1MDViMmU0ODMzODA3MTViYjM5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pPq4Y76cY_ofZDgrJesVs1T2cTFA1GOiphpuYWYKaBQ">

**Update 2 Feb 2024:**

You may need to install `nbclassic` to the get the widget item in the menu bar, see: https://github.com/jupyter/nbclassic 

Install: 

```
pip install nbclassic
```

Run:

```
jupyter nbclassic
```

Otherwise clearing the widget metadata as discussed above may work too, however, I'm not 100% sure.

**Comment by nfultz** [comment]
I hit this bug today, here was my workaround using jq to delete the widgets block from the shell, maybe someone else finds that helpful:

```
! jq  "del(.metadata.widgets)" "/content/drive/MyDrive/Colab Notebooks/etl-3.ipynb" > /tmp/test.ipynb
```

**Comment by mrdbourke** [comment]
> Just hit with https://colab.research.google.com/github/kstathou/vector_engine/blob/master/notebooks/001_vector_search.ipynb
> 
> The workaround recommended by **@pplonski** worked for me. Here is what I did
> 
> 1. Download 001_vector_search.ipynb with Colab gui
> 2. Fail to convert it with nbconvert
> 
> ```
> % jupyter nbconvert --to html 001_vector_search.ipynb
>   [NbConvertApp] Converting notebook 001_vector_search.ipynb to html
>   Traceback (most recent call last):
>     File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
>       sys.exit(main())
>     File "/usr/local/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
>       return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
>     ...
>     File "/usr/local/share/jupyter/nbconvert/templates/base/display_priority.j2", line 7, in block 'data_priority'
>       {%- for type in output.data | filter_data_type -%}
>     File "/usr/local/lib/python3.9/site-packages/nbconvert/filters/widgetsdatatypefilter.py", line 57, in __call__
>       metadata["widgets"][WIDGET_STATE_MIMETYPE]["state"]
>   KeyError: 'state'
> ```
> 
> 3. Remove .metadata.widgets with Jq
> 
> ```
> % jq -M 'del(.metadata.widgets)' 001_vector_search.ipynb > 001_vector_search.fixed.ipynb
> % jupyter nbconvert --to html 001_vector_search.fixed.ipynb
>   [NbConvertApp] Converting notebook 001_vector_search.fixed.ipynb to html
>   [NbConvertApp] Writing 629781 bytes to 001_vector_search.fixed.html
> 
> % open 001_vector_search.fixed.html
> 
>   ... output looks good
> ```
> 
> For reference I'm on OSX 10.15.7 and here are my jupyter versions
> 
> ```
> % jupyter --version
>   Selected Jupyter core packages...
>   IPython          : 8.0.1
>   ipykernel        : 6.9.0
>   ipywidgets       : not installed
>   jupyter_client   : 7.1.2
>   jupyter_core     : 4.9.1
>   Jupyter_server   : not installed
>   jupyterlab       : not installed
>   nbclient         : 0.6.4
>   nbconvert        : 6.5.0
>   nbformat         : 5.4.0
>   notebook         : not installed
>   qtconsole        : not installed
>   traitlets        : 5.2.2
> ```

Slight modification for this command to work in-place. 

Because `jq` requires saving to another file, you can't just do `notebook.ipynb > notebook.ipynb`.

You can save to temp and then then `mv` to original filename.

```
jq -M 'del(.metadata.widgets)' NOTEBOOK_NAME.ipynb > NOTEBOOK_NAME.temp.ipynb && mv NOTEBOOK_NAME.temp.ipynb NOTEBOOK_NAME.ipynb
```

**Comment by ulisesrey** [comment]
If it helps anyone, I usually use Jupyterlab instead of Jupyternotebook. I did not find the widgets tab on Jupyterlab, even after installing 

> ```shell
> pip install ipywidgets
> ```

But I could find it in JupyterNotebook and then I did it from there.

**Comment by GregO2020** [comment]
I have tried all the workarounds and none work. Finally went to another PC to run the following code in a PC Windows 10 system prompt: jupyter nbconvert NBfile.ipynb --to html
The first time it worked, but then I got the same error mentioned above: error metadata["widgets"][WIDGET_STATE_MIMETYPE]["state"] KeyError: 'state'
I used that command successfully for six months, dozens of times. All of a sudden, I cannot convert to html

**Comment by fjadidi2001** [comment]
You can resolve this problem by installing the nbstripout package using pip install nbstripout

**Comment by mua-dib** [comment]
This will work in colab:

!jupyter nbconvert --to html --execute your_notebook.ipynb

note that it will run a debug.

**Comment by tituatgithub** [comment]
You can handle this with nbconvert itself using:

nbconvert --clear-output --inplace your_notebook.ipynb

or via Python:

from nbconvert.preprocessors import ClearOutputPreprocessor
import nbformat

with open("your_notebook.ipynb") as f:
    nb = nbformat.read(f, as_version=4)

ClearOutputPreprocessor().preprocess(nb, {})

with open("your_notebook.ipynb", "w") as f:
    nbformat.write(nb, f)

That said, I found this workflow a bit repetitive when dealing with multiple notebooks (having to pass file paths and rerun it each time).

I ended up putting together a small tool for myself that removes outputs + redundant metadata in one go and can be reused easily without worrying about paths each time.

Sharing in case it helps:
https://muffin-tools.pages.dev/tools/notebook-cleaner

Also nice that since it’s simple and built on open stuff, I don’t have to worry about privacy of my notebooks.

**Comment by hpy1968** [comment]
I’ve opened a PR that should address this here: https://github.com/jupyter/nbconvert/pull/2288.

The failure seems to happen when the notebook metadata contains the widget-state mimetype object, but that object does not include a nested `"state"` key. `WidgetsDataTypeFilter` currently indexes that key unconditionally, which raises `KeyError: "state"`.

The proposed change treats missing `"state"` the same as unavailable widget state, so the filter falls back to the next available display format instead of crashing.

**Comment by Bendoair** [comment]
for me this worked:
run in cmd:
python -c "import json; f=open('YOUR_NOTEBOOK.ipynb', 'r', encoding='utf-8'); d=json.load(f); f.close(); d['metadata'].pop('widgets', None); f=open('YOUR_NOTEBOOK.ipynb', 'w', encoding='utf-8'); json.dump(d, f, indent=1); print('Metadata cleaned successfully!')"
then export as usual.
