### ISSUE TITLE
Getting Error when running nbconvert command  : ImportError: cannot import name 'contextfilter' from 'jinja2' 

### ISSUE THREAD

**Issue by amish44** [jupyter/nbconvert#1742]
When running nbconvert command getting below error  :
Stack Trace:
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/usr/local/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 14, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)

Command:
jupyter nbconvert --execute --TemplateExporter.exclude_input=True --stdout --no-input --inplace --allow-errors --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=python /test.ipynb

**Nbconvert version:** 

nbconvert                         6.1.0

**Comment by qzhang234** [comment]
I'm running into this too. Would really appreciate some help

**Comment by qzhang234** [comment]
I did `conda install jinja2` and now I got a different error with `xelatex`:

```
(work) PS E:\work\2022_RheoXPCS> jupyter nbconvert --to pdf .\Read_C2_Write_CCS.ipynb
[NbConvertApp] Converting notebook .\Read_C2_Write_CCS.ipynb to pdf
[NbConvertApp] Support files will be in Read_C2_Write_CCS_files\
[NbConvertApp] Making directory .\Read_C2_Write_CCS_files
[NbConvertApp] Making directory .\Read_C2_Write_CCS_files
[NbConvertApp] Making directory .\Read_C2_Write_CCS_files
[NbConvertApp] Writing 32912 bytes to notebook.tex
[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "C:\Users\qzhang234\Anaconda3\envs\work\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\jupyter_core\application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\nbconvertapp.py", line 518, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\nbconvertapp.py", line 483, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\nbconvertapp.py", line 412, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\exporters\exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\exporters\pdf.py", line 183, in from_notebook_node
    self.run_latex(tex_file)
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\exporters\pdf.py", line 153, in run_latex
    return self.run_command(self.latex_command, filename,
  File "C:\Users\qzhang234\Anaconda3\envs\work\lib\site-packages\nbconvert\exporters\pdf.py", line 110, in run_command
    raise OSError("{formatter} not found on PATH, if you have not installed "
OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/inst
all.html#installing-tex.
(work) PS E:\work\2022_RheoXPCS>
```

**Comment by pawlodkowski** [comment]
Also ran into this issue with `nbconvert==6.1.0`. Strange as I've been using the same script for months now without any problem, with all versions of dependencies fixed to the specific versions. Is it possible that this older version of nbconvert got some kind of bug retroactively?

**Comment by bollwyvl** [comment]
> Jinja2 3.1.1

as the title suggests, `jinja 3.1.x`, one of the key upstreams of nbconvert, has deprecated a number of APIs. You might be able to pin to `jinja<3.1` if you are relying on some bug/feature, but #1737 and subsequent have been released, restoring this compatibility. 

we'll be trying to ensure better coverage of this in the future, and stay as compatible as possible, but as a tool _and_ a library relied upon by other packages, it's rather hard for us to just blanket pin dependency versions, see #1740.

> nbconvert==6.1.0

As has been suggested in a number of places related to this, if you start hard pinning individual values of dependencies, you likely need to pin, and check in, a _complete_ solution to your environment, including all transient dependencies, and critically evaluate when you are forced to re-solve, e.g. because of security concerns.

A number of tools make this more tractable, such as:
- [pip-tools](https://github.com/jazzband/pip-tools)
- [conda-lock](https://github.com/conda-incubator/conda-lock)

**Comment by proinsias** [comment]
Still seeing this issue with nbconvert 6.5.0. Had to pin jinja2<3.1.

**Comment by scchess** [comment]
`pip install nbconvert==6.4.3` worked for me.

**Comment by lneuhaus** [comment]
`pip install nbconvert --upgrade` solved this for me.

**Comment by nevakrien** [comment]
same issue rn on a new environment with everything baseline other than intel-pytorch-extension. 
tried playing with the tornado version since it helped me last time this error came up. 

in genral this is really anoying because its on jupyter notebook which I use for alot of things and i see this error once a month

**Comment by MostafaaElhadidy** [comment]
> `pip install nbconvert==6.4.3` worked for me.

this actually worked! thanks
