### ISSUE TITLE
nbconvert export fails for HTML & PDF on macOS Monterey 12.3.1

### ISSUE THREAD

**Issue by guger** [jupyter/nbconvert#1773]
**Description**
I want to export a pdf of my jupyter notebook (.ipynb) file, but this doesn't work, as it can't resolve the template_path.

**Stacktrace:**
```
jupyter nbconvert --to html SymMeasNodeNet.ipynb
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 582, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 101, in get_exporter
    if getattr(exporter(config=config), "enabled", True):
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 341, in __init__
    super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 117, in __init__
    self._init_preprocessors()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _init_preprocessors
    conf = self._get_conf()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 525, in _get_conf
    for path in map(Path, self.template_paths):
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 536, in _template_paths
    template_names = self.get_template_names()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 620, in get_template_names
    raise ValueError(
ValueError: No template sub-directory with name 'lab' found in the following paths:
	/Users/dguger/Library/Jupyter
	/Users/dguger/Library/Python/3.9/share/jupyter
	/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter
```

**Can you list steps to reproduce this issue?**

Try to export a file using `nbconvert` on macOS.

**Environment Data:**

- OS: macOS Monterey 12.3.1
- Python version: 3.9.12
- Jupyter server running: Local
- LaTeX version: MacTex Version 3.141592653 (TeX Live 2021)
- **nbconvert: 6.5.0**
- jupyter: 1.0.0
- jupyter-core: 4.10.0

**Comment by guger** [comment]
The issue is still present in v7.0.0rc1!

**Comment by hyt658** [comment]
I have the same issue, hope can get solution soon :D

**Comment by guger** [comment]
The error does also occur when using a venv. Every Python environment I use is based on a homebrew installation.

Does anybody know if this is a homebrew-specific error or does anybody also experience this on non-homebrew installations of Python on macOS?

What is your installation method and OS? @hyt658

**Comment by hyt658** [comment]
> 

I installed via homebrew as well

**Comment by Mills-2** [comment]
Any updates on this?

**Comment by guger** [comment]
6.5.1 does not change anything...

**Comment by PaleNeutron** [comment]
Any updates on it? I found a tmp [workaround](https://github.com/executablebooks/jupyter-book/issues/1541#issuecomment-1166064740)

And this bug breaks my [projects test](https://github.com/dexplo/dataframe_image/runs/7998310078?check_suite_focus=true)

**Comment by bartoli** [comment]
As mentionned in the last linked issue, i am getting the error after jupyter has been installed using 'pip install jupyter --prefix=XXXX'. Templates are properly installed, but in XXXX/jupyter/share/nbconvert/templates, and i guess they are searched in PYTHON_ROOT/share/... ?

**Comment by bartoli** [comment]
In my case, this is 'fixed' by adding 

root_dirs.append(os.path.abspath(os.path.join(ROOT, "..", "..", "..", "..", "share", "jupyter")))

to get_prefix_root_dirs() in nbconvert/exporters/templateexporter.py.

Worst case, this adds a folder that is a duplicate of PYTHON_ROOT/share/jupyter if it is a standard install. A 'smart' condition could be added to avoid adding it if we detect that we are installed in python folder. Or this path could replace PYTHON_ROOT/share/jupyter in the list alltogether?

**Comment by GabeNicholson** [comment]
Still having this issue with the most recent version with M1 Mac and home-brew. Not sure if there are any known fixes?

**Comment by guger** [comment]
@bartoli Unfortunately, that does not solve the issue for me.

**Comment by kgrodzicki** [comment]
> Still having this issue with the most recent version with M1 Mac and home-brew. Not sure if there are any known fixes?

Extending the JUPYTER_PATH with /opt/homebrew/share/jupyter works for me.  

```shell
export JUPYTER_PATH=/opt/homebrew/share/jupyter:$JUPYTER_PATH
```

**Comment by guger** [comment]
@kgrodzicki I tried that, but in my case, the path isn't recognized either. I've commented that here: https://github.com/jupyter/jupyter_core/issues/250#issuecomment-1284523635

**Comment by LPascholatti** [comment]
@kgrodzicki the workaround helped me! Thanks!
