### ISSUE TITLE
nbconvert failed: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by tgsheng** [jupyter/nbconvert#1789]
When I try to export a notebook as a tex or pdf file, it reports an error: 
```
500 : Internal Server Error
The error was: nbconvert failed: Expecting value: line 1 column 1 (char 0)
```
I don't know how to solve it?
The error message:
```
YAML parse exception at line 1, column 0,
while scanning for the next token:
found character that cannot start any token
[E 2022-06-09 16:01:47.298 ServerApp] nbconvert failed: Expecting value: line 1 column 1 (char 0)
    Traceback (most recent call last):
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\nbconvert\handlers.py", line 131, in get
        output, resources = await run_sync(
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
        return await future
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 284, in __await__
        yield self  # This tells Task to wait for completion.
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 304, in __wakeup
        future.result()
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
        raise self._exception
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
        result = context.run(func, *args)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\nbconvert\handlers.py", line 132, in <lambda>
        lambda: exporter.from_notebook_node(nb, resources=resource_dict)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\latex.py", line 74, in from_notebook_node
        return super().from_notebook_node(nb, resources, **kw)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\templateexporter.py", line 400, in from_notebook_node
        output = self.template.render(nb=nb_copy, resources=resources)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
        self.environment.handle_exception()
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\index.tex.j2", line 8, in top-level template code
        ((* extends cell_style *))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\style_jupyter.tex.j2", line 176, in top-level template code
        \prompt{(((prompt)))}{(((prompt_color)))}{(((execution_count)))}{(((extra_space)))}
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\base.tex.j2", line 7, in top-level template code
        ((*- extends 'document_contents.tex.j2' -*))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\document_contents.tex.j2", line 51, in top-level template code
        ((*- block figure scoped -*))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\display_priority.j2", line 5, in top-level template code
        ((*- extends 'null.j2' -*))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\null.j2", line 30, in top-level template code
        ((*- block body -*))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\base.tex.j2", line 215, in block 'body'
        ((( super() )))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\null.j2", line 32, in block 'body'
        ((*- block any_cell scoped -*))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\null.j2", line 85, in block 'any_cell'
        ((*- block markdowncell scoped-*)) ((*- endblock markdowncell -*))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\document_contents.tex.j2", line 68, in block 'markdowncell'
        ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\filters\filter_links.py", line 17, in resolve_references
        return applyJSONFilters([resolve_one_reference], source)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\site-packages\pandocfilters.py", line 203, in applyJSONFilters
        doc = json.loads(source)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\tgs\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[W 2022-06-09 16:01:47.396 ServerApp] 500 GET /nbconvert/latex/Solutions.ipynb?download=true (::1): nbconvert failed: Expecting value: line 1 column 1 (char 0)
[E 2022-06-09 16:01:47.460 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33"
    }
[E 2022-06-09 16:01:47.460 ServerApp] 500 GET /nbconvert/latex/Solutions.ipynb?download=true (::1) 1163.05ms referer=http://localhost:8888/lab
```

Actually, I have exported successfully yesterday.

**Comment by tgsheng** [comment]
I have solved it. It parsed my horizontal lines `---` as `YAML`...

**Comment by ikki4** [comment]
So the "solution" is to delete the --- lines? Isn't there anything else that can be done?

**Comment by Debe2003** [comment]
@tgsheng THANKS for sharing your solution. I just experienced the same problem.

**Comment by jaun-van-heerden** [comment]
The issue arises with the "---" still.
Is there any active conversation around this? - cheers
