### ISSUE TITLE
nbconvert failed: 'state'

### ISSUE THREAD

**Issue by ElmWer** [jupyter/nbconvert#1811]
converting a ipynb file (to whatever, pdf, html, ...) is failing with error code 'state* but only if  ipynb file has output cells

**Error message using jupyter lab export function**
500 : Internal Server Error
The error was: nbconvert failed: 'state'

**Error message running nbconvert in terminal**
$ jupyter nbconvert --to html test.ipynb
[NbConvertApp] Converting notebook test.ipynb to html
Traceback (most recent call last):
  File "D:\apps\Miniconda3\Scripts\jupyter-nbconvert-script.py", line 9, in <module>
    sys.exit(main())
  File "D:\apps\Miniconda3\lib\site-packages\jupyter_core\application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "D:\apps\Miniconda3\lib\site-packages\traitlets\config\application.py", line 976, in launch_instance
    app.start()
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 588, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 551, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 479, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 189, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 206, in from_file
    return self.from_notebook_node(
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\exporters\html.py", line 215, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 400, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "D:\apps\Miniconda3\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\apps\Miniconda3\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\index.html.j2", line 3, in top-level template code
    {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 260, in top-level template code
    {% set div_id = uuid4() %}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 26, in top-level template code
    {%- block body -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 29, in block 'body'
    {%- block body_loop -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 31, in block 'body_loop'
    {%- block any_cell scoped -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 34, in block 'any_cell'
    {%- block codecell scoped -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 12, in block 'codecell'
    {{ super() }}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 44, in block 'codecell'
    {%- block output_group -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 38, in block 'output_group'
    {{ super() }}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 48, in block 'output_group'
    {%- block outputs scoped -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 44, in block 'outputs'
    {{ super() }}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 50, in block 'outputs'
    {%- block output scoped -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 87, in block 'output'
    {{ super() }}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\null.j2", line 52, in block 'output'
    {%- block execute_result scoped -%}{%- endblock execute_result -%}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 114, in block 'execute_result'
    {% block data_priority scoped %}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\lab\base.html.j2", line 115, in block 'data_priority'
    {{ super() }}
  File "D:\apps\Miniconda3\share\jupyter\nbconvert\templates\base\display_priority.j2", line 7, in block 'data_priority'
    {%- for type in output.data | filter_data_type -%}
  File "D:\apps\Miniconda3\lib\site-packages\nbconvert\filters\widgetsdatatypefilter.py", line 57, in __call__
    metadata["widgets"][WIDGET_STATE_MIMETYPE]["state"]
KeyError: 'state'

**Nbconvert version:**
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.4
nbclient         : 0.6.6
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.3.0

**Comment by salcc** [comment]
Possible duplicate of https://github.com/jupyter/nbconvert/issues/1731.

**Comment by patrickm663** [comment]
Facing the same issue, but only on _some_ notebooks. I was able to resolve this by clearing the notebook widget state via "Widgets" --> "Clear Notebook Widgets State" as per https://github.com/jupyter/nbconvert/issues/1731#issuecomment-1292573781. If widgets aren't installed, they can be installed via:

```
pip install ipywidgets
```
