### ISSUE TITLE
nbconvert broken distribution

### ISSUE THREAD

**Issue by wvxvw** [jupyter/nbconvert#1819]
Trivial install with `setuptools` from the current newest Jupyter is broken:

using this `setup.py`:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup


if __name__ == '__main__':
    setup(
        install_requires=(
            'notebook',
        ),
    )

```

```
Installing nbconvert-7.0.0rc3-py3-none-any.whl to /home/wvxvw/<secret>/.venv/lib/python3.8/site-packages
Traceback (most recent call last):
  File "./setup.py", line 8, in <module>
    setup(
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 744, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 855, in install_eggs
    return [install_dist(dist_filename, tmpdir)]
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1070, in install_wheel
    self.execute(
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 335, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/usr/local/lib/python3.8/distutils/util.py", line 303, in execute
    func(*args)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 114, in _convert_metadata
    wheel_metadata = get_metadata('WHEEL')
  File "/home/wvxvw/<secret>/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 110, in get_metadata
    with zf.open(posixpath.join(dist_info, name)) as fp:
  File "/usr/local/lib/python3.8/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/WHEEL' in the archive"
```
Looks like you've uploaded a broken archive to PyPI.

**Comment by wvxvw** [comment]
In addition: why do you even package tests? Users don't need them. Please only put them in a source tarball, not in a distributable package.

**Comment by TiagodePAlves** [comment]
Couldn't reproduce this, `pip install nbconvert==7.0.0rc3` is working for me. Tested in a fresh Python 3.8 virutal env and a fresh Python 3.10 too. What are yout system specs? Maybe I could repro in a Docker.

And I agree, tests should be removed from bdists...
