### ISSUE TITLE
ValueError when converting SVG figure

### ISSUE THREAD

**Issue by adl** [jupyter/nbconvert#1836]
Hi

Trying to convert a notebook containing some SVG image like [issue.ipynb](https://github.com/jupyter/nbconvert/files/9366210/issue.txt) to html, I now get an exception from nbconvert 6.5.1 (as packaged by Debian Unstable).  I did not have a problem with version 6.4.4.

```
% jupyter nbconvert issue.ipynb --to html
[NbConvertApp] Converting notebook issue.ipynb to html
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 33, in <module>
    sys.exit(load_entry_point('nbconvert==6.5.1', 'console_scripts', 'jupyter-nbconvert')())
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 423, in start
    self.convert_notebooks()
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 560, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 488, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 189, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 206, in from_file
    return self.from_notebook_node(
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/html.py", line 225, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/templateexporter.py", line 416, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/share/jupyter/nbconvert/templates/lab/index.html.j2", line 3, in top-level template code
    {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 280, in top-level template code
    {% set div_id = uuid4() %}
  File "/usr/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 26, in top-level template code
    {%- block body -%}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 29, in block 'body'
    {%- block body_loop -%}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 31, in block 'body_loop'
    {%- block any_cell scoped -%}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 34, in block 'any_cell'
    {%- block codecell scoped -%}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 12, in block 'codecell'
    {{ super() }}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 44, in block 'codecell'
    {%- block output_group -%}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 38, in block 'output_group'
    {{ super() }}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 48, in block 'output_group'
    {%- block outputs scoped -%}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 44, in block 'outputs'
    {{ super() }}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 50, in block 'outputs'
    {%- block output scoped -%}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 87, in block 'output'
    {{ super() }}
  File "/usr/share/jupyter/nbconvert/templates/base/null.j2", line 52, in block 'output'
    {%- block execute_result scoped -%}{%- endblock execute_result -%}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 125, in block 'execute_result'
    {% block data_priority scoped %}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 126, in block 'data_priority'
    {{ super() }}
  File "/usr/share/jupyter/nbconvert/templates/base/display_priority.j2", line 12, in block 'data_priority'
    {%- block data_svg -%}
  File "/usr/share/jupyter/nbconvert/templates/lab/base.html.j2", line 162, in block 'data_svg'
    {{ output.data['image/svg+xml'] | clean_html }}
  File "src/lxml/html/clean.py", line 562, in lxml.html.clean.Cleaner.clean_html
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 761, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1908, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by emarsden** [comment]
Pull request #1837 should fix this problem.

**Comment by adl** [comment]
While #1837 fixes the exception, it does not fixes the rendering.   Tags inside the SVG object seems to have been completely removed, and the output is rendered as a byte sequence`b'...'` enclosing the samaged `<svg>` object.  Here is what I see in the example notebook that was attached to my first comment:

![Screenshot from 2022-08-30 17-06-03](https://user-images.githubusercontent.com/822900/187475152-05ac6954-5d77-45ad-909b-92e0d07c607b.png)

**Comment by emarsden** [comment]
This is true. I have fixed this in my local copy using simply

   {{ output.data['image/svg+xml'] }}

(no "cleaning" of the SVG content), but this may have security consequences that I have not attempted to assess for the general case.

**Comment by JBlaschke** [comment]
For all those following along -- What ended up doing the trick is was editing the base template located at: `<installation prefix>/share/jupyter/nbconvert/templates/lab`:
```diff
$ diff base.html.j2 base.html.j2.old
166c166
< {{ output.data['image/svg+xml'] }}
---
> {{ output.data['image/svg+xml'].encode("utf-8") | clean_html }}
```
As @emarsden said, this probably has security implications, but I was just looking for something that'll let me generate Reveal.js slides again.
