### ISSUE TITLE
Failed validating <unset> in notebook on instance <unset>

### ISSUE THREAD

**Issue by trevorcampbell** [jupyter/nbconvert#1872]
Hi Jupyter team,

I'm getting an odd error when trying to clear the output of a notebook. For context: this is an assignment notebook submitted by a student in my R datascience class, and students often break notebooks in various ways. Normally I can figure out what the student did and fix the raw ipynb JSON myself, but this error message is so unclear that I really do not know where to start.

**steps to reproduce:** Luckily we do everything in our course in a docker image, so you can reproduce this easily:
- download the attached `main.ipynb`
- navigate to the folder containing the notebook
- run `docker run --rm -it -v $(pwd):/home/jovyan ubcdsci/r-dsci-100-grading:v0.32.0 /bin/bash`
- inside the docker container, run `jupyter nbconvert --inplace --clear-output main.ipynb`

The output then looks like the following:
```
jovyan@39833e9ffe2f:~$ jupyter nbconvert --inplace --clear-output main.ipynb 
[NbConvertApp] Converting notebook main.ipynb to notebook
[NbConvertApp] ERROR | Notebook JSON is invalid: data.cells[{data__cells_x}] must be valid exactly by one definition (0 matches found)

Failed validating <unset> in notebook['data']['cells']:

On instance:
<unset>
[NbConvertApp] ERROR | Notebook is invalid after preprocessor <nbconvert.preprocessors.tagremove.TagRemovePreprocessor object at 0x7f41dae69390>
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 588, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 551, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 479, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 189, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 206, in from_file
    return self.from_notebook_node(
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/exporters/notebook.py", line 35, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 146, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 337, in _preprocess
    self._validate_preprocessor(nbc, preprocessor)
  File "/opt/conda/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 307, in _validate_preprocessor
    nbformat.validate(nbc, relax_add_props=True)
  File "/opt/conda/lib/python3.10/site-packages/nbformat/validator.py", line 302, in validate
    raise error
nbformat.validator.NotebookValidationError: data.cells[{data__cells_x}] must be valid exactly by one definition (0 matches found)

Failed validating <unset> in notebook['data']['cells']:

On instance:
<unset>
```

The relevant bit is:
```
Notebook JSON is invalid: data.cells[{data__cells_x}] must be valid exactly by one definition (0 matches found)

Failed validating <unset> in notebook['data']['cells']:

On instance:
<unset>
```
which tells the user no useful information about how to handle the issue.

By the way, I did run it through `jsonlint`, which confirmed that the JSON itself is valid. So it's just not following the assumed notebook format.

Thanks!

**Nbconvert version:** 6.5.0

**Comment by kcarnold** [comment]
I encountered this problem with nbformat 5.4.0 installed. Upgrading nbformat (to 5.7.3) made the error message much more helpful.

I think the "confusing error message" part of this bug is resolved. However, the validation is quite picky (e.g., not allowing additional properties on cells), probably more picky than needed for most conversion tasks.

**Comment by m5c** [comment]
Here's an unorthodox but efficient solution for *markdown cells with ```outputs``` property*:
=> run a regex search-and-replace to wipe all empty output properties of the entire document.

```python
import re
with open('MyNotebook.ipynb', 'r') as file:
    jupyter = file.read()
    outputs_tag_removed = re.sub(',\n\s+\"outputs\":\ \[\]', '', jupyter)
    print(outputs_tag_removed, file=open('MyNotebook.ipynb', 'w'))
```

I first tried to do this with ```sed``` but regex matching across line-breaks is not supported by ```sed```, therefore the python script.
Hope it helps.
I based my solution on [this corruption checker](https://stackoverflow.com/a/56014817). Turned out in my case the errors were always the markdown-cells-with-outputs corruptions.
