### ISSUE TITLE
jupyter export as pdf does not work in vscode

### ISSUE THREAD

**Issue by ordinarylhy** [jupyter/nbconvert#1928]
I want to export jupyter notebook as pdf in vscode, but get the following error.

I have tex installed on my macbook:
homefolder@Hellos-MacBook-Pro-2 ~ % tex
This is TeX, Version 3.141592653 (TeX Live 2022) (preloaded format=tex)

don't know why this error occurs.
thanks!

the error message is below:

Visual Studio Code (1.74.2, undefined, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.20.1.
No workspace folder opened.
warn 16:06:42.648: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.8
    loaded from: /Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/zeromq

	at load.path (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/zeromq/lib/native.js:1:198)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
	at w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/zeromq/lib/index.js:1:144)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
	at w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at 92747 (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:442832)
	at __webpack_require__ (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:1241219)
	at c.zmqSupported (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2187160)
	at c.isSupportedForLocalLaunch (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2186903)
	at get isSupported [as isSupported] (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2186813)
	at t.registerTypes (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2202584)
	at /Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576202
	at /Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576861
	at /Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576869
	at t.activate (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576991)
	at Ln.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:15127)
	at Ln.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:14825)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:12823
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async v.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:7006)
	at async v.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:6969)
	at async v.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:6426)]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 16:06:42.834: LSP Notebooks experiment is enabled
info 16:06:43.094: Find preferred kernel for /Users/homefolder/Desktop/exercise-indexing-selecting-assigning.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}} & preferred interpreter /usr/bin/python3
info 16:06:43.094: Find preferred kernel for /Users/homefolder/Desktop/exercise-indexing-selecting-assigning.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}} & preferred interpreter /usr/bin/python3
info 16:06:43.102: Find preferred kernel for /Users/homefolder/Desktop/exercise-indexing-selecting-assigning.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}} & preferred interpreter /usr/bin/python3
info 16:06:43.187: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], false, false)
info 16:06:43.187: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/homefolder/Desktop/exercise-indexing-selecting-assigning.ipynb
info 16:06:43.193: Find preferred kernel for /Users/homefolder/Desktop/exercise-indexing-selecting-assigning.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}} & preferred interpreter /usr/bin/python3
info 16:06:43.194: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 16:06:43.194: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/homefolder/Desktop/exercise-indexing-selecting-assigning.ipynb
info 16:06:43.231: Got empty env vars with python /usr/bin/python3 in 136ms
info 16:06:43.231: Got empty env vars with python /usr/bin/python3 in 135ms
info 16:06:43.232: Got empty env vars with python /usr/bin/python3 in 136ms
info 16:06:43.232: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
info 16:06:43.233: Process Execution: > /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
info 16:06:43.233: Process Execution: > /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -c "import notebook"
info 16:06:43.320: Process Execution: > /usr/bin/python3 -m jupyter kernelspec --version
> /usr/bin/python3 -m jupyter kernelspec --version
info 16:06:43.325: Got empty env vars with python /usr/bin/python3 in 6ms
info 16:06:43.466: Got empty env vars with python /usr/bin/python3 in 11ms
info 16:06:43.466: Got empty env vars with python /usr/bin/python3 in 11ms
info 16:06:48.486: Process Execution: > /usr/bin/python3 -c "import nbconvert"
> /usr/bin/python3 -c "import nbconvert"
info 16:06:48.498: Got empty env vars with python /usr/bin/python3 in 13ms
info 16:06:48.726: Process Execution: > /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
info 16:06:48.731: Got empty env vars with python /usr/bin/python3 in 6ms
info 16:06:48.753: Process Execution: > /usr/bin/python3 -m jupyter nbconvert /var/folders/m_/7f2q0cyx3t7943h54s9lkbl00000gn/T/e6ff9e05-06e7-4ff0-9ef8-dec45e42e634/exercise-indexing-selecting-assigning.ipynb --to pdf --output tmp-39149w0SWC2eX99LW.pdf --output-dir /var/folders/m_/7f2q0cyx3t7943h54s9lkbl00000gn/T --debug
> /usr/bin/python3 -m jupyter nbconvert /var/folders/m_/7f2q0cyx3t7943h54s9lkbl00000gn/T/e6ff9e05-06e7-4ff0-9ef8-dec45e42e634/exercise-indexing-selecting-assigning.ipynb --to pdf --output tmp-39149w0SWC2eX99LW.pdf --output-dir /var/folders/m_/7f2q0cyx3t7943h54s9lkbl00000gn/T --debug
info 16:06:48.758: Got empty env vars with python /usr/bin/python3 in 6ms
error 16:06:49.264: Export failed [Error: [NbConvertApp] Searching ['/', '/Users/homefolder/.jupyter', '/Users/homefolder/Library/Python/3.9/etc/jupyter', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/homefolder/Library/Python/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/homefolder/.jupyter
[NbConvertApp] Looking for jupyter_config in /
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/homefolder/Library/Python/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/homefolder/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /
[NbConvertApp] Converting notebook /var/folders/m_/7f2q0cyx3t7943h54s9lkbl00000gn/T/e6ff9e05-06e7-4ff0-9ef8-dec45e42e634/exercise-indexing-selecting-assigning.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-39149w0SWC2eX99LW'
[NbConvertApp] Template paths:
	/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex
	/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/base
	/Users/homefolder/Library/Jupyter
	/Users/homefolder/Library/Jupyter/nbconvert/templates
	/Users/homefolder/Library/Jupyter/nbconvert/templates/compatibility
	/Users/homefolder/Library/Python/3.9/share/jupyter
	/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates
	/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/compatibility
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter/nbconvert/templates
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter/nbconvert/templates/compatibility
	/usr/local/share/jupyter
	/usr/local/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter/nbconvert/templates/compatibility
	/usr/share/jupyter
	/usr/share/jupyter/nbconvert/templates
	/usr/share/jupyter/nbconvert/templates/compatibility
	/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template index.tex.j2
[NbConvertApp]     template_paths: /Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex:/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/base:/Users/homefolder/Library/Jupyter:/Users/homefolder/Library/Jupyter/nbconvert/templates:/Users/homefolder/Library/Jupyter/nbconvert/templates/compatibility:/Users/homefolder/Library/Python/3.9/share/jupyter:/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates:/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/compatibility:/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter:/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter/nbconvert/templates:/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates
[NbConvertApp] ERROR | Error while converting '/var/folders/m_/7f2q0cyx3t7943h54s9lkbl00000gn/T/e6ff9e05-06e7-4ff0-9ef8-dec45e42e634/exercise-indexing-selecting-assigning.ipynb'
Traceback (most recent call last):
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/exporters/exporter.py", line 207, in from_file
    return self.from_notebook_node(
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/exporters/pdf.py", line 181, in from_notebook_node
    latex, resources = super().from_notebook_node(nb, resources=resources, **kw)
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/exporters/latex.py", line 74, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/exporters/templateexporter.py", line 401, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/index.tex.j2", line 8, in top-level template code
    ((* extends cell_style *))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2", line 176, in top-level template code
    \prompt{(((prompt)))}{(((prompt_color)))}{(((execution_count)))}{(((extra_space)))}
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 7, in top-level template code
    ((*- extends 'document_contents.tex.j2' -*))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 51, in top-level template code
    ((*- block figure scoped -*))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/display_priority.j2", line 5, in top-level template code
    ((*- extends 'null.j2' -*))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/null.j2", line 30, in top-level template code
    ((*- block body -*))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 215, in block 'body'
    ((( super() )))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/null.j2", line 32, in block 'body'
    ((*- block any_cell scoped -*))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/null.j2", line 85, in block 'any_cell'
    ((*- block markdowncell scoped-*)) ((*- endblock markdowncell -*))
  File "/Users/homefolder/Library/Python/3.9/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 68, in block 'markdowncell'
    ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/filters/pandoc.py", line 24, in convert_pandoc
    return pandoc(source, from_format, to_format, extra_args=extra_args)
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/utils/pandoc.py", line 51, in pandoc
    check_pandoc_version()
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/utils/pandoc.py", line 99, in check_pandoc_version
    v = get_pandoc_version()
  File "/Users/homefolder/Library/Python/3.9/lib/python/site-packages/nbconvert/utils/pandoc.py", line 76, in get_pandoc_version
    raise PandocMissing()
nbconvert.utils.pandoc.PandocMissing: Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
[NbConvertApp] Exiting application: jupyter-nbconvert

	at S.executeCommand (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2471107)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async a.export (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2480606)
	at async f.exportToFormat (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2492159)
	at async f.performNbConvertExport (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2491963)
	at async f.performExport (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2491618)
	at async f.exportImpl (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2491136)
	at async f.export (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2490860)
	at async t.ExportCommands.export (/Users/homefolder/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:200860)
	at async s.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107614)]
error 16:06:49.264: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.

**Comment by tuncbkose** [comment]
Feel free to reopen if needed.

**Comment by tuncbkose** [comment]
@Drakit0 You don't seem to have the same error, given how your error message implies you probably don't have `xelatex` installed. Have you tried looking at the link it tells you to look at?
