### ISSUE TITLE
Cannot convert to HTML

### ISSUE THREAD

**Issue by MagedSaeed** [jupyter/nbconvert#2033]
Dears,

I cannot convert a file to HTML. The error I am getting is:

```
Traceback (most recent call last):
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 186, in <module>
    class NbConvertApp(JupyterApp):
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 245, in NbConvertApp
    Options include {get_export_names()}.
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 151, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 110, in get_exporter
    exporter = items[0].load()
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/jupyter_contrib_nbextensions/__init__.py", line 5, in <module>
    import jupyter_nbextensions_configurator
  File "/home/majed.alshaibani/.virtualenvs/tmp-9eb99bfb2d88dd0/lib/python3.8/site-packages/jupyter_nbextensions_configurator/__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'
```

with the command:
```
jupyter nbconvert --to html "notebook.ipynb"
```

Packages (from pip freeze):
```
anyio==3.7.1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
async-lru==2.0.4
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==2.1.1
comm==0.1.4
debugpy==1.6.7.post1
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.1.3
executing==1.2.0
fastjsonschema==2.18.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.1
ipykernel==6.25.1
ipython==8.12.2
ipython-genutils==0.2.0
ipywidgets==8.1.0
jedi==0.19.0
Jinja2==3.1.2
json5==0.9.14
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-client==8.3.0
jupyter-console==6.6.3
jupyter-contrib-core==0.4.2
jupyter-contrib-nbextensions==0.7.0
jupyter-core==5.3.1
jupyter-events==0.7.0
jupyter-highlight-selected-word==0.2.0
jupyter-lsp==2.2.0
jupyter-nbextensions-configurator==0.6.3
jupyter-server==2.7.2
jupyter-server-terminals==0.4.4
jupyterlab==4.0.5
jupyterlab-pygments==0.2.2
jupyterlab-server==2.24.0
jupyterlab-widgets==3.0.8
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mistune==3.0.1
nbclient==0.8.0
nbconvert==7.7.4
nbformat==5.9.2
nest-asyncio==1.5.7
notebook==7.0.2
notebook-shim==0.2.3
overrides==7.4.0
packaging==23.1
pandocfilters==1.5.0
parso==0.8.3
pdfkit==1.0.0
pexpect==4.8.0
pickleshare==0.7.5
pkgutil-resolve-name==1.3.10
platformdirs==3.10.0
prometheus-client==0.17.1
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
python-dateutil==2.8.2
python-json-logger==2.0.7
python-slugify==7.0.0
pytz==2023.3
PyYAML==6.0.1
pyzmq==25.1.1
qtconsole==5.4.3
QtPy==2.3.1
referencing==0.30.2
requests==2.28.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.9.2
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
terminado==0.17.1
text-unidecode==1.3
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.3
traitlets==5.9.0
typing-extensions==4.7.1
urllib3==1.26.16
wcwidth==0.2.6
webencodings==0.5.1
websocket-client==1.6.1
widgetsnbextension==4.0.8
zipp==3.16.2
```

Is there anything I am missing?

**Comment by MagedSaeed** [comment]
seem that removing nbextensions solves the issue. Do not know why, btw.

```
pip uninstall jupyter-contrib-nbextensions jupyter-nbextensions-configurator
```

**Comment by tuncbkose** [comment]
Not sure exactly how all the different packages interacted to result in this. But you have `jupyterlab>4` and `notebook>7` so all the `nbextensions` stuff shouldn't be needed anymore, because `notebook>7` is written using JupyterLab components.

No `nbconvert` problem here as far as I can tell.
