### ISSUE TITLE
[Python] Inconsistent failures in the presence of invalid syntax

### ISSUE THREAD

**Issue by kycutler** [jupyter/nbconvert#2047]
When converting to Python, most types of syntax issues in code cells will not result in failure. For example, these all succeed:

```python
print(
```

```python
print("hello")
    print("world")
```

```python
&(&*$%)^@362\262ew:.1
```

```python
for i in range(10):
    print(i)
        print(i)
```

However, the following code will result in a failure due to `IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)`:

```python
for i in range(10):
        print(i)
    print(i)
```

It seems weirdly inconsistent for this to fail, and the others not.

**Comment by broukema** [comment]
@kycutler  There's a [4MOST CRS tools bug](https://github.com/4most-crs/4MOST_CRS_tools/issues/1) that gives `IndentationError: unindent does not match any outer indentation level`. This might give a clue regarding the current bug.

Any idea where the syntax error is in [the source file test.ipynb](https://github.com/4most-crs/4MOST_CRS_tools/blob/main/CRStools/test.ipynb) ?  (No point viewing it directly in the MS/GH web interface - it includes a lot .png files.

**Comment by broukema** [comment]
### Minimal working example (mwe):

I found the outdent error. Here's a minimal example that fails:

````
$ cat mwe.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class MyGreatFunction(object):\n",
    "    \"\"\"Description of function.\"\"\"\n",
    "  @classmethod\n",
    "    def myfunction()\n",
    "        print(\"hello world\")\n",
    "        return 1"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "whatever",
   "language": "python",
   "name": "whatever"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
$ jupyter nbconvert mwe.ipynb --to python
[NbConvertApp] Converting notebook mwe.ipynb to python
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 33, in <module>
    sys.exit(load_entry_point('nbconvert==6.5.3', 'console_scripts', 'jupyter-nbconvert')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 982, in launch_instance
    app.start()
...
  File "/usr/lib/python3/dist-packages/IPython/core/inputtransformer2.py", line 510, in make_tokens_by_line
    for token in tokenize.generate_tokens(iter(lines).__next__):
  File "/usr/lib/python3.11/tokenize.py", line 516, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 3
    @classmethod
IndentationError: unindent does not match any outer indentation level
````

### Fix
The problem is the line `    "  @classmethod\n",` that has only two indent spaces instead of four. Here's exactly the same source, but with two extra spaces inserted; this converts OK:
````
$ cat mwe_fixed.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class MyGreatFunction(object):\n",
    "    \"\"\"Description of function.\"\"\"\n",
    "    @classmethod\n",
    "    def myfunction()\n",
    "        print(\"hello world\")\n",
    "        return 1"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "whatever",
   "language": "python",
   "name": "whatever"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
$ jupyter nbconvert mwe_fixed.ipynb --to python
[NbConvertApp] Converting notebook mwe_fixed.ipynb to python
[NbConvertApp] Writing 201 bytes to mwe_fixed.py
$
````

My understanding is that `nbconvert` was correct to refuse to do the conversion in this (4MOST_CRS_tools) case. So I do not have a new example of `nbconvert` having incorrect behaviour beyond the original example (with `for/print/print`) by @kycutler . (I'm not actually convinced that the `for/print/print` example should be considered correct python - a python engine will not know whether the second `print` statement is intended to be inside the `for` loop or outside the `for` loop.)
