### ISSUE TITLE
Error with usc package when exporting .ipynb to pdf file 

### ISSUE THREAD

**Issue by hfzheng** [jupyter/nbconvert#2113]
23:22:54.317 [info] Process Execution: ~/anaconda3/bin/python -m jupyter nbconvert /var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/HW2_P2.ipynb --to pdf --output tmp-10617hhcvjIfaykC.pdf --output-dir /var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T --debug
23:22:56.306 [error] Export failed [Error: [NbConvertApp] Searching ['/', '~/.jupyter', '~/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_config in /
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /
[NbConvertApp] Converting notebook /var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/HW2_P2.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-10617hhcvjIfaykC.pdf'
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template article.tplx
[NbConvertApp]     template_path: .
[NbConvertApp] Writing 15504 bytes to /var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', '/var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/notebook.tex']
[NbConvertApp] CRITICAL | xelatex failed: ['xelatex', '/var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/notebook.tex']
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/notebook.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-18>
(~/Library/TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(~/Library/TinyTeX/texmf-dist/tex/latex/base/size11.clo)) (~/Library/TinyTeX/texmf-dist/tex/latex/base/fontenc.sty (~/Library/TinyTeX/texmf-dist/tex/latex/lm/t1lmr.fd)) (~/Library/TinyTeX/texmf-dist/tex/latex/psnfss/mathpazo.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/trig.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics-def/xetex.def))) (~/Library/TinyTeX/texmf-dist/tex/latex/caption/caption.sty (~/Library/TinyTeX/texmf-dist/tex/latex/caption/caption3.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/adjustbox.sty (~/Library/TinyTeX/texmf-dist/tex/latex/xkeyval/xkeyval.sty (~/Library/TinyTeX/texmf-dist/tex/generic/xkeyval/xkeyval.tex (~/Library/TinyTeX/texmf-dist/tex/generic/xkeyval/xkvutils.tex))) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/adjcalc.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/trimclip.sty (~/Library/TinyTeX/texmf-dist/tex/latex/collectbox/collectbox.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/tc-xetex.def))) (~/Library/TinyTeX/texmf-dist/tex/latex/xcolor/xcolor.sty (~/Library/TinyTeX/texmf-dist/tex/latex/graphics-cfg/color.cfg) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/mathcolor.ltx)) (~/Library/TinyTeX/texmf-dist/tex/latex/tools/enumerate.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty (~/Library/TinyTeX/texmf-dist/tex/generic/iftex/ifvtex.sty (~/Library/TinyTeX/texmf-dist/tex/generic/iftex/iftex.sty))) (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amstext.sty (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsgen.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsbsy.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsopn.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/amssymb.sty (~/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/amsfonts.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/base/textcomp.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/upquote/upquote.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/eurosym/eurosym.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/ucs/ucs.sty

Package ucs Warning: ucs package ignored with utf8 based engines.

)

! LaTeX Error: Unknown option `mathletters' for package `ucs'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55     \usepackage
                    [utf8x]{inputenc} % Allow utf-8 characters in the tex do...
? 
! Emergency stop.
 ...                                              
                                                  
l.55     \usepackage
                    [utf8x]{inputenc} % Allow utf-8 characters in the tex do...
No pages of output.
Transcript written on notebook.log.

Traceback (most recent call last):
  File "~/anaconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "~/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "~/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 493, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 464, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "~/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/pdf.py", line 183, in from_notebook_node
    raise LatexFailed('\n'.join(self._captured_output))
nbconvert.exporters.pdf.LatexFailed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/var/folders/32/_29s9hb51gjbhrsnk7pwx_x80000gn/T/99930077-6159-405a-97f1-4e618ce319b2/notebook.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-18>
(~/Library/TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(~/Library/TinyTeX/texmf-dist/tex/latex/base/size11.clo)) (~/Library/TinyTeX/texmf-dist/tex/latex/base/fontenc.sty (~/Library/TinyTeX/texmf-dist/tex/latex/lm/t1lmr.fd)) (~/Library/TinyTeX/texmf-dist/tex/latex/psnfss/mathpazo.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/trig.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics-def/xetex.def))) (~/Library/TinyTeX/texmf-dist/tex/latex/caption/caption.sty (~/Library/TinyTeX/texmf-dist/tex/latex/caption/caption3.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/adjustbox.sty (~/Library/TinyTeX/texmf-dist/tex/latex/xkeyval/xkeyval.sty (~/Library/TinyTeX/texmf-dist/tex/generic/xkeyval/xkeyval.tex (~/Library/TinyTeX/texmf-dist/tex/generic/xkeyval/xkvutils.tex))) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/adjcalc.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/trimclip.sty (~/Library/TinyTeX/texmf-dist/tex/latex/collectbox/collectbox.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/adjustbox/tc-xetex.def))) (~/Library/TinyTeX/texmf-dist/tex/latex/xcolor/xcolor.sty (~/Library/TinyTeX/texmf-dist/tex/latex/graphics-cfg/color.cfg) (~/Library/TinyTeX/texmf-dist/tex/latex/graphics/mathcolor.ltx)) (~/Library/TinyTeX/texmf-dist/tex/latex/tools/enumerate.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty (~/Library/TinyTeX/texmf-dist/tex/generic/iftex/ifvtex.sty (~/Library/TinyTeX/texmf-dist/tex/generic/iftex/iftex.sty))) (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amstext.sty (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsgen.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsbsy.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsopn.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/amssymb.sty (~/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/amsfonts.sty)) (~/Library/TinyTeX/texmf-dist/tex/latex/base/textcomp.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/upquote/upquote.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/eurosym/eurosym.sty) (~/Library/TinyTeX/texmf-dist/tex/latex/ucs/ucs.sty

Package ucs Warning: ucs package ignored with utf8 based engines.

)

**! LaTeX Error: Unknown option `mathletters' for package `ucs'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55     \usepackage
                    [utf8x]{inputenc} % Allow utf-8 characters in the tex do...
? 
! Emergency stop.
 ...**                                              
                                                  
l.55     \usepackage
                    [utf8x]{inputenc} % Allow utf-8 characters in the tex do...
No pages of output.
Transcript written on notebook.log.

	at v_.executeCommand (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:321796)
	at async x_.export (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:325661)
	at async M_.exportToFormat (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:330132)
	at async M_.performNbConvertExport (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:329960)
	at async M_.performExport (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:329635)
	at async M_.exportImpl (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:329263)
	at async M_.export (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:329019)
	at async $C.export (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-arm64/out/extension.node.js:24:470042)
	at async n.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:84275)]
23:22:56.307 [error] If you have not installed xelatex (TeX), you will need to do so before you can export to PDF. For further instructions, please see https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX), you might want to try exporting to HTML and using your browser's "Print to PDF" feature.

**Comment by raedma** [comment]
I can reproduce the problem and am also very interested in a solution. Running on Windows with MikTeX and `ucs` version 2.4 which is the current [CTAN](https://ctan.org/pkg/ucs) release. However, the version installed by the MikTeX package manager is 2.4 from `Thu Nov 16 10:51:38 2023` and the CTAN release is from `2023-11-09` with the same number 2.4.

**Comment by hfzheng** [comment]
Thank you!
