### ISSUE TITLE
webpdf JSONDecodeError: Expecting value: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by JostBrand** [jupyter/nbconvert#2125]
The test file contains only one print statement. When running the command: `jupyter nbconvert --to webpdf .\test.ipynb  --template classic --allow-error` I get the following error. 

Traceback:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "xxx\.venv\Scripts\jupyter-nbconvert.EXE\__main__.py", line 4, in <module>
  File "xxx\.venv\Lib\site-packages\nbconvert\__init__.py", line 6, in <module>
    from . import filters, postprocessors, preprocessors, writers
  File "xxx\.venv\Lib\site-packages\nbconvert\filters\__init__.py", line 8, in <module>
    from .markdown import (
  File "xxx\.venv\Lib\site-packages\nbconvert\filters\markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "xxx\.venv\Lib\site-packages\nbconvert\filters\markdown_mistune.py", line 22, in <module>
    from nbconvert.filters.strings import add_anchor
  File "xxx\.venv\Lib\site-packages\nbconvert\filters\strings.py", line 23, in <module>
    from nbconvert.preprocessors.sanitize import _get_default_css_sanitizer
  File "xxx\.venv\Lib\site-packages\nbconvert\preprocessors\__init__.py", line 3, in <module>
    from nbclient.exceptions import CellExecutionError
  File "xxx\.venv\Lib\site-packages\nbclient\__init__.py", line 2, in <module>
    from .client import NotebookClient, execute
  File "xxx\.venv\Lib\site-packages\nbclient\client.py", line 19, in <module>
    from nbformat import NotebookNode
  File "xxx\.venv\Lib\site-packages\nbformat\__init__.py", line 14, in <module>
    from . import v1, v2, v3, v4
  File "xxx\.venv\Lib\site-packages\nbformat\v4\__init__.py", line 24, in <module>
    from .convert import downgrade, upgrade
  File "xxx\.venv\Lib\site-packages\nbformat\v4\convert.py", line 12, in <module>
    from nbformat import v3, validator
  File "xxx\.venv\Lib\site-packages\nbformat\validator.py", line 16, in <module>
    from .json_compat import ValidationError, _validator_for_name, get_current_validator
  File "xxx\.venv\Lib\site-packages\nbformat\json_compat.py", line 12, in <module>
    import jsonschema
  File "xxx\.venv\Lib\site-packages\jsonschema\__init__.py", line 16, in <module>
    from jsonschema.validators import (
  File "xxx\.venv\Lib\site-packages\jsonschema\validators.py", line 20, in <module>
    from jsonschema_specifications import REGISTRY as SPECIFICATIONS
  File "xxx\.venv\Lib\site-packages\jsonschema_specifications\__init__.py", line 10, in <module>
    REGISTRY = (_schemas() @ _EMPTY_REGISTRY).crawl()
                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  File "xxx\.venv\Lib\site-packages\referencing\_core.py", line 378, in __rmatmul__
    for resource in new:
  File "xxx\.venv\Lib\site-packages\jsonschema_specifications\_core.py", line 37, in _schemas
    contents = json.loads(path.read_text(encoding="utf-8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
 `

Package List:
```
Package                   Version
------------------------- -----------
asttokens                 2.4.1
attrs                     23.2.0
beautifulsoup4            4.12.3
bleach                    6.1.0
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.2.0
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
et-xmlfile                1.1.0
executing                 2.0.1
fastjsonschema            2.19.1
fonttools                 4.49.0
greenlet                  3.0.3
ipykernel                 6.29.3
ipython                   8.22.2
jedi                      0.19.1
Jinja2                    3.1.3
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter_client            8.6.1
jupyter_core              5.7.2
jupyterlab_pygments       0.3.0
kiwisolver                1.4.5
MarkupSafe                2.1.5
matplotlib                3.8.3
matplotlib-inline         0.1.6
mistune                   3.0.2
nb_pdf_template           4.0.0
nbclient                  0.10.0
nbconvert                 7.16.2
nbformat                  5.10.2
nest-asyncio              1.6.0
numpy                     1.26.4
openpyxl                  3.1.2
packaging                 24.0
pandas                    2.2.1
pandocfilters             1.5.1
parso                     0.8.3
pillow                    10.2.0
pip                       24.0
platformdirs              4.2.0
playwright                1.42.0
prompt-toolkit            3.0.43
psutil                    5.9.8
pure-eval                 0.2.2
pyee                      11.0.1
Pygments                  2.17.2
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
pytz                      2024.1
pywin32                   306
pyzmq                     25.1.2
referencing               0.33.0
rpds-py                   0.18.0
six                       1.16.0
soupsieve                 2.5
stack-data                0.6.3
tinycss2                  1.2.1
tornado                   6.4
traitlets                 5.14.2
typing_extensions         4.10.0
tzdata                    2024.1
wcwidth                   0.2.13
webencodings              0.5.1
```

**Comment by MrVeka** [comment]
Hey, I have got the same error I think : 
```
Error importing optional module nbformat
Traceback (most recent call last):
  File "xxx\.venv\Lib\site-packages\_plotly_utils\optional_imports.py", line 28, in get_module
    return import_module(name)
           ^^^^^^^^^^^^^^^^^^^
  File "xxx\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "xxx\.venv\Lib\site-packages\nbformat\__init__.py", line 14, in <module>
    from . import v1, v2, v3, v4
  File "xxx\.venv\Lib\site-packages\nbformat\v4\__init__.py", line 24, in <module>
    from .convert import downgrade, upgrade
  File "xxx\.venv\Lib\site-packages\nbformat\v4\convert.py", line 12, in <module>
    from nbformat import v3, validator
  File "xxx\.venv\Lib\site-packages\nbformat\validator.py", line 17, in <module>
    from .json_compat import ValidationError, _validator_for_name, get_current_validator
  File "xxx\.venv\Lib\site-packages\nbformat\json_compat.py", line 13, in <module>
    import jsonschema
  File "xxx\.venv\Lib\site-packages\jsonschema\__init__.py", line 16, in <module>
    from jsonschema.validators import (
  File "xxx\.venv\Lib\site-packages\jsonschema\validators.py", line 20, in <module>
    from jsonschema_specifications import REGISTRY as SPECIFICATIONS
  File "xxx\.venv\Lib\site-packages\jsonschema_specifications\__init__.py", line 11, in <module>
    REGISTRY = (_schemas() @ _EMPTY_REGISTRY).crawl()
                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  File "xxx\.venv\Lib\site-packages\referencing\_core.py", line 384, in __rmatmul__
    for resource in new:
                    ^^^
  File "xxx\.venv\Lib\site-packages\jsonschema_specifications\_core.py", line 37, in _schemas
    contents = json.loads(path.read_text(encoding="utf-8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```
Package List:

```
Package                   Version
------------------------- -----------
asttokens                 3.0.0
attrs                     24.2.0
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.1
cycler                    0.12.1
debugpy                   1.8.9
decorator                 5.1.1
executing                 2.1.0
fastjsonschema            2.21.1
fonttools                 4.55.2
ipykernel                 6.29.5
ipython                   8.30.0
jedi                      0.19.2
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter_client            8.6.3
jupyter_core              5.7.2
kiwisolver                1.4.7
matplotlib                3.9.3
matplotlib-inline         0.1.7
nbformat                  5.10.4
nest-asyncio              1.6.0
numpy                     2.1.3
packaging                 24.2
pandas                    2.2.3
parso                     0.8.4
pillow                    11.0.0
pip                       24.3.1
platformdirs              4.3.6
plotly                    5.24.1
prompt_toolkit            3.0.48
psutil                    6.1.0
pure_eval                 0.2.3
Pygments                  2.18.0
pyparsing                 3.2.0
python-dateutil           2.9.0.post0
pytz                      2024.2
pywin32                   308
pyzmq                     26.2.0
referencing               0.35.1
rpds-py                   0.22.3
scikit-learn              1.5.2
scipy                     1.14.1
seaborn                   0.13.2
six                       1.17.0
stack-data                0.6.3
tenacity                  9.0.0
threadpoolctl             3.5.0
tornado                   6.4.2
traitlets                 5.14.3
tzdata                    2024.2
wcwidth                   0.2.13
```

For context, I'm working on some data, and to do so want to use these libraries :

```
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.figure_factory as ff
from sklearn.mixture import BayesianGaussianMixture
from scipy.stats import multivariate_normal
```
Plotly has working just fine, I was adding the libraries as I needed them, and suddenly, as I restart the Jupyter Kernel, it gives me the error message.  

From my tests, no versions from >=5.0.0 work, and older ones get this error because of 3.9>= python : 
`ImportError: cannot import name 'encodestring' from 'base64'`

**Comment by garncarz** [comment]
There was a `---` in a Markdown cell in the notebook I was trying to export and it led to this very error, seemingly totaly unrelated. Changing it to `-----` helped.
