### ISSUE TITLE
nbconvert does not return when kernel cannot start

### ISSUE THREAD

**Issue by aggFTW** [jupyter/nbconvert#217]
Hi,

I was trying to execute a notebook with nbconvert but the command never returned. This notebook was executing against a custom kernel; note that executing against a python2 kernel notebook worked fine.

I tried executing from python:
```
$ sudo /usr/bin/anaconda/bin/python
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>import nbformat
>>>from nbconvert.preprocessors import ExecutePreprocessor
>>>ep = ExecutePreprocessor(timeout=300, kernel_name='python2')
>>>with open("pyspark_error.ipynb") as f:
           nb = nbformat.read(f, as_version=4)
>>>ep.preprocess(nb, {'metadata': {'path': "/var/lib/sparkmagiclibs/tests"}})
^CTraceback (most recent call last):
  File "/usr/bin/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/bin/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/lib/sparkmagiclibs/integrationtesting/test_magics_e2e.py", line 59, in <module>
    main(args.path[0])
  File "/var/lib/sparkmagiclibs/integrationtesting/test_magics_e2e.py", line 38, in main
    if not runner.run(notebook_path, notebook_path_out):
  File "integrationtesting/runner.py", line 29, in run
    self.ep.preprocess(nb, {'metadata': {'path': self.run_path}})
  File "/usr/bin/anaconda/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    cwd=path)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 433, in start_new_kernel
    kc.wait_for_ready()
  File "/usr/bin/anaconda/lib/python2.7/site-packages/jupyter_client/blocking/client.py", line 22, in wait_for_ready
    msg = self.shell_channel.get_msg(block=True)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/jupyter_client/blocking/channels.py", line 50, in get_msg
    ready = self.socket.poll(timeout)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/zmq/sugar/socket.py", line 503, in poll
    evts = dict(p.poll(timeout))
  File "/usr/bin/anaconda/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1705)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2084)
KeyboardInterrupt
```

Then I realized that Anaconda's IPython could not find the package for the kernel because it wasn't in the path, so when I started Python like so, it worked:
`$ sudo PATH=/usr/bin/anaconda/bin:$PATH /usr/bin/anaconda/bin/python`

Shouldn't nbconvert raise an exception if the kernel cannot be started?

**Comment by aggFTW** [comment]
FYI @msftristew @MohamedElKamhawy

**Comment by takluyver** [comment]
For me, it does raise an error if it can't start the kernel:

```
FileNotFoundError: [Errno 2] No such file or directory: 'oij'
```

If the command that it runs starts but isn't responding as a kernel, it should time out after a while.

**Comment by takluyver** [comment]
See jupyter/jupyter_client#118.
