### ISSUE TITLE
env should not contain unicode

### ISSUE THREAD

**Issue by JanSchulz** [jupyter/nbconvert#218]
Using nbconvert on py2.7 results in the following error:

```
Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\jupyter-nbconvert-script.py", line 5, in <module>
    main()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\portabel\miniconda\lib\site-packages\traitlets\config\application.py", line 589, in launch_instance
    app.start()
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\nbconvertapp.py", line 289, in start
    self.convert_notebooks()
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\nbconvertapp.py", line 412, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\nbconvertapp.py", line 383, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\nbconvertapp.py", line 335, in export_single_notebook

    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\exporters\exporter.py", line 165, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\exporters\pdf.py", line 146, in from_notebook_node
    rc = self.run_latex(tex_file)
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\exporters\pdf.py", line 109, in run_latex
    self.latex_count, log_error)
  File "C:\portabel\miniconda\lib\site-packages\nbconvert\exporters\pdf.py", line 89, in run_command
    p = subprocess.Popen(command, stdout=stdout, stdin=null, shell=shell, env=env)
  File "C:\portabel\miniconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\portabel\miniconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

It seems that you are not allowed to use unicode strings, at least the following makes it work:

```python
       if shell:
            command = subprocess.list2cmdline(command)
        env = os.environ.copy()
-       env['TEXINPUTS'] = os.pathsep.join([self.texinputs, env.get('TEXINPUTS', '')])
+       env['TEXINPUTS'] = str(os.pathsep.join([self.texinputs, env.get('TEXINPUTS', '')]))
        with open(os.devnull, 'rb') as null:
            stdout = subprocess.PIPE if not self.verbose else None
            for index in range(count):
```

**Comment by minrk** [comment]
This was fixed by #165
