### ISSUE TITLE
not working if jupyter_contrib_nbextensions are installed

### ISSUE THREAD

**Issue by hoba87** [jupyter/nbconvert#2189]
I tried to convert a Jupyter notebook to python script with `jupyter nbconvert --to python ...`

This gave me an error if outdated? jupyter_contrib_nbextension is installed:
```
Traceback (most recent call last):
  File "/opt/python/python-3.10.10/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/opt/python/python-3.10.10/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 193, in <module>
    class NbConvertApp(JupyterApp):
  File "/opt/python/python-3.10.10/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 252, in NbConvertApp
    Options include {get_export_names()}.
  File "/opt/python/python-3.10.10/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 145, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/opt/python/python-3.10.10/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 106, in get_exporter
    exporter = items[0].load()
  File "/opt/python/python-3.10.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/opt/python/python-3.10.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/python/python-3.10.10/lib/python3.10/site-packages/jupyter_contrib_nbextensions/nbconvert_support/__init__.py", line 5, in <module>
    from .collapsible_headings import ExporterCollapsibleHeadings
  File "/opt/python/python-3.10.10/lib/python3.10/site-packages/jupyter_contrib_nbextensions/nbconvert_support/collapsible_headings.py", line 6, in <module>
    from notebook.services.config import ConfigManager
ModuleNotFoundError: No module named 'notebook.services'
```

However, when I uninstall it, it works.

**Comment by krassowski** [comment]
This issue is in `jupyter_contrib_nbextensions` and should be reported over there.

**Comment by blaiseli** [comment]
I have a similar problem, and I would like to point out that I was somehow "forced" to install jupyter_contrib_nbextensions.

I start from a fresh virtual env:
```
$ /home/bli/python3.11/bin/python3 -m venv .venv
$ source .venv/bin/activate
$ pip install --upgrade pip
$ pip install nbconvert
```

I check that `jupyter nbconvert --help` works:

```
$ jupyter nbconvert --help
```

Output looks OK.

Then I try the following command:
```
$ jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True Make_vsRNA_graphs.ipynb --output tmp.ipynb
```

This ends up with the following error:
```
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
```

**Is this error due to the particular type of conversion I'm asking `jupyter nbconvert` to perform? Or can this be related to the content of my notebook?**

Anyway, I proceed to install jupyter_contrib_nbextensions:

```
$ pip install jupyter_contrib_nbextensions
```

But then `jupyter nbconvert --help` fails as follows:

```
    from notebook.services.config import ConfigManager
ModuleNotFoundError: No module named 'notebook.services'
```

(Same error with `jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True Make_vsRNA_graphs.ipynb --output tmp.ipynb`)

Some of the latest issues regarding jupyter_contrib_nbextensions suggest me that it will be hard to get a fix on their side:

https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1661

https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1666

https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1667


Pull requests seem to be pending since quite some time:
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pulls

**Comment by blaiseli** [comment]
Fixes discussed here work for me:
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1663#issuecomment-2248001870

I forked the fork on which the above pull request is based and added the extra modification to `src/jupyter_contrib_nbextensions/nbconvert_support/execute_time.py`:

https://github.com/blaiseli/jupyter_contrib_nbextensions

Then:
```
pip uninstall jupyter_contrib_nbextensions
pip install git+https://github.com/blaiseli/jupyter_contrib_nbextensions
```

Now `jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True Make_vsRNA_graphs.ipynb --output tmp.ipynb` doesn't crash any more.
