### ISSUE TITLE
SVG images are not rendered in latex export

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#244]
This is a bit of a tricky one I guess.
By default latex doesn't support svg images, but they are a nice format if you want to show vector graphics in a browser. I could convert to png but that seems not great.
there is a svg package that could be used to convert svg packages to pdf on the fly.

**Comment by jakobgager** [comment]
Actually svgs should be converted to pdf using inkscape during the nbconversion. How do you use/embed the svg?

**Comment by amueller** [comment]
``![some_svg](some.svg)`` in a markup cell. I'll try a minimal reproduction later.

**Comment by amueller** [comment]
Ok, so I did ``![svg_thing](overfitting_underfitting_cartoon.svg)`` which gave me

```
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.255 ...ics{overfitting_underfitting_cartoon.svg}
                                                  
? 
! Emergency stop.
 ...                                              
                                                  
l.255 ...ics{overfitting_underfitting_cartoon.svg}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.
```
when trying to convert to pdf.

the generated latex is
```latex
    \begin{figure}[htbp]
\centering
\includegraphics{overfitting_underfitting_cartoon.svg}
\caption{svg\_thing}
\end{figure}
```

**Comment by amueller** [comment]
kinda unrelated, I guess, but when I do "download pdf" on that page, after the latex build fails, I get
```
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1450, in _execute
        self._handle_request_exception(e)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1502, in _handle_request_exception
        self.send_error(e.status_code, exc_info=sys.exc_info())
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 978, in send_error
        self.finish()
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/home/andy/anaconda3/lib/python3.5/json/__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "/home/andy/anaconda3/lib/python3.5/json/encoder.py", line 201, in encode
        chunks = list(chunks)
      File "/home/andy/anaconda3/lib/python3.5/json/encoder.py", line 436, in _iterencode
        o = _default(o)
      File "/home/andy/anaconda3/lib/python3.5/json/encoder.py", line 180, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x7fdb52d96b70> is not JSON serializable
```
on the console where I started the notebook server.

**Comment by jakobgager** [comment]
You are right. In your particular case only the syntax is converted from markdown to latex but the linked content not. 
If the svg data is embedded in the notebook, e.g. created by a matplotlib plot this svg data is converted during the extraction to pdf. Hence, it would be a good idea to write a preprocessor which captures all linked content and converts is as required. Here, it would be possible a well to download images which are linked via a web address.

**Comment by michaelpacer** [comment]
Is there a reason this is better to have as a jupyter extension rather than as part of core nbconvert preprocessors?

@Carreau, @takluyver, @minrk  how do we determine what goes in the extensions repo and what is incorporated into core projects? Is there a system for migrating things? This seems like important svg support and may address other issues that I'm having difficulty finding right now.

**Comment by amueller** [comment]
I agree with @michaelpacer that this would be good to have in the main repo.

**Comment by takluyver** [comment]
@michaelpacer sometimes we ask people to make an extension if something is too specific for the main repos, or we're not sure about how to design it. But in this case, it's an extension largely because @juhasch, who maintains the repo with a collection of extensions, got round to doing it.

There's no system to migrate things to or from extensions, it would just involve making a pull request like any other feature.

Note that we [already have](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/svg2pdf.py) svg2pdf conversion, but as @jakobgager said, it doesn't currently handle svgs linked into the notebook in markdown cells.

**Comment by romor001** [comment]
Ran into this issue when trying to convert my notebooks contaning SVG images in Markdown into Pdf.
Any workaround recommended other than converting the SVGs to PNG?

**Comment by MichaelAdolph** [comment]
@romor001  I also ran into trouble with converting SVGs. I hunted down the problem, and indeed: there are two problems:

Some specs: I'm using jupyter-nbconvert 6.0.7 on python 3.8.6, windows PC.
Inkscape is installed into the default folder C:\Program Files\Inkscape

And here is the first problem, the whitespace in "Program Files" makes the call fail, because it is not enclosed in double quotes or in another way escaped. 

The second problem is that the initial --export-filename will raise an error because auf an overwriting risk, it should be changed to --export-type. But than you have to change the value (from a filename to just "pdf").

All in all I change the site-packages\nbconvert\preprocessors\svg2pdf.py the following way:

```python
    @default('command')
    def _command_default(self):
        self.inkscape_path_string = f'\"{self.inkscape}\"' # added this to escape the whitespace
        major_verison = self.inkscape_version.split('.')[0]
        export_option = ' --export-type' if int(major_verison) > 0 else ' --export-pdf'
        gui_option = '' if int(major_verison) > 0 else ' --without-gui'
        to_filename = 'pdf' if int(major_verison) > 0 else to_filename # Need this for backward-capability

        return '{inkscape}{gui_option}{export_option}='.format(
            inkscape=self.inkscape_path_string, export_option=export_option, gui_option=gui_option
        ) + f'{to_filename}' + " {from_filename}" # needed to update the string, otherwise it did not work for my (but that is probably my fault)
```

No converting Jupyter Notebooks works.

All look at a way to update the package and create a pull request.

**Comment by MichaelAdolph** [comment]
I added a pull request for this issue #1469 , this should also work for issue #1325

**Comment by aravindh-krishnamoorthy** [comment]
https://github.com/jupyter/nbconvert/pull/2190: Here's a workaround that hooks onto `\includegraphics` and replaces it with `\includesvg` for SVG files. But the resulting LaTeX files need `-shell-escape` to compile as `\includesvg` uses Inkscape for conversion, see also issue https://github.com/jupyter/nbconvert/issues/2192.

I understand that `-shell-escape` may not be secure and might allow malicious users to include arbitrary commands in a Python notebook, which will activate during LaTeX compilation or export.

On the other hand, I also do not think messing with `![](file.svg)` in a markdown cell and converting it to PDF on the fly is a good idea.

So, not sure what's the best way forward here.
