### ISSUE TITLE
nbconvert --execute sporadically fails

### ISSUE THREAD

**Issue by msftristew** [jupyter/nbconvert#277]
When I try to execute my Python2 notebook at the command line, it will sporadically fail reporting that the kernel died:

    [Anaconda2] C:\git\Monarch\package\HDPAzureIaaS\hdinsight-jupyter\src\IntegrationTesting\tests>jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute Untitled1.ipynb
    [NbConvertApp] Converting notebook Untitled1.ipynb to notebook
    [NbConvertApp] Executing notebook with kernel: python2
    Traceback (most recent call last):
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\Scripts\jupyter-nbconvert-script.py", line 5, in <module>
        main()
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\traitlets\config\application.py", line 589, in launch_instance
        app.start()
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 289, in start
        self.convert_notebooks()
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 412, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 383, in convert_single_notebook
        output, resources = self.export_single_notebook(notebook_filename, resources)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 335, in export_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\exporters\exporter.py", line 165, in from_filename
        return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\exporters\notebook.py", line 26, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\exporters\exporter.py", line 130, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\exporters\exporter.py", line 302, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
        return self.preprocess(nb,resources)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\nbconvert\preprocessors\execute.py", line 79, in preprocess
        cwd=path)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 433, in start_new_kernel
        kc.wait_for_ready(timeout=startup_timeout)
      File "C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\jupyter_client\blocking\client.py", line 49, in wait_for_ready
        raise RuntimeError('Kernel died before replying to kernel_info')
    RuntimeError: Kernel died before replying to kernel_info

I get this error seemingly randomly -- sometimes it's more often than others, but it seems to fail with this error about half the time overall.  I've seen this error on both Linux and Windows.

I wasn't able to figure out what's going on by poking around the code.  It seems that the code is simply [checking whether the kernel process died](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L414) and that the process is reported as being dead -- confusing, because when I start these kernels from Jupyter, they don't die randomly like this.

Manually putting some code together following the directions [here](https://github.com/jupyter/nbconvert/blob/master/docs/source/execute_api.rst) also sporadically fails with this exception.

CC @aggFTW, @MohamedElKamhawy

**Comment by minrk** [comment]
What do you get from `conda list`? We have some work to fix this in the latest versions of a few packages. Can you check with the latest versions of nbconvert and jupyter-client (4.2 of both, I think)?

**Comment by msftristew** [comment]
I have the most recent version of `jupyter_client`, but it looks like I only have 4.1 of `nbconvert` (it looks like the most recent version was released on [Friday](https://pypi.python.org/pypi/nbconvert)?)

I'll update `nbconvert` and give it a shot.

**Comment by msftristew** [comment]
Just upgraded `nbconvert` to 4.2.0 and still getting the same error.

**Comment by lgautier** [comment]
I am experiencing the same, with the only difference that it is consistently failing with that error (I did not have one successful run so far).

```$ jupyter nbconvert --version
4.2.0
```

**Comment by brazilbean** [comment]
Same problem here. Sporadic failures using the ExecutePreprocessor class. I am not running via nbconvert, but have written a package that uses a child class of ExecutePreprocessor to process the notebook. In other words, I get the same failure using the nbconvert API.

```
jupyter                   1.0.0                    py35_3
jupyter_client            4.2.2                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
```

**Comment by yerfdogyrag** [comment]
@brazilbean, it looks like this is a similar issue.  https://github.com/jupyter/jupyter_client/issues/142  .  What's odd is that they say it's fixed in 4.2.2, but I moved to 4.2.2 but am still seeing some of the hard-coded timeouts in client.py.

**Comment by michaelpacer** [comment]
Is this still an issue?

**Comment by lgautier** [comment]
It was still when checked few weeks ago. 

`nbconvert` is called through `docker run` and noticed recently that the Docker images from the jupyter project were using `tini` (because of issues when not doing so). 

I'll check if the problem persists with `tini` as an `ENTRYPOINT`

**Comment by akimd** [comment]
I have a similar problem in my project, where we run a tool (https://gitlab.lrde.epita.fr/vcsn/vcsn/blob/master/tests/bin/ipynbdoctest.py) in batch mode to verify that the input/output in the notebook are still up-to-date.  Sort of a test suite.  The code we have is:

```python
    km = KernelManager()
    # Do not save the history to disk, as it can yield spurious lock errors.
    # See https://github.com/ipython/ipython/issues/2845
    km.start_kernel(extra_arguments=['--HistoryManager.hist_file=:memory:'],
                    stderr=subprocess.DEVNULL)
    kc = km.client()
    kc.start_channels()
    kc.wait_for_ready()
```

and on occasion, the test suite fails with:

```
Traceback (most recent call last):
  File "/srv/teamcity-agent/work/a0185dad9234e013/tests/bin/ipynbdoctest.py", line 279, in <module>
    success &= test_notebook(os.path.basename(ipynb))
  File "/srv/teamcity-agent/work/a0185dad9234e013/tests/bin/ipynbdoctest.py", line 204, in test_notebook
    kc.wait_for_ready()
  File "/usr/lib/python3.5/site-packages/jupyter_client/blocking/client.py", line 59, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

**Comment by andilabs** [comment]
any updates on it? 

Running `nbconvert==5.4.1` and still getting the error
```
[...]
File "/z/projectx/virtual_envs/20190403T093238/Ubuntu16.04/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 251, in start_new_kernel
    kc.wait_for_ready(timeout=self.startup_timeout)
  File "/z/projectx/virtual_envs/20190403T093238/Ubuntu16.04/lib/python3.5/site-packages/jupyter_client/blocking/client.py", line 120, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

**Comment by MSeal** [comment]
Likely this is a setup issue with resourcing. NBconvert 5.5 had some improvements, 5.5.1 which is the next release has some kernel timeout improvements and I haven't seen this error in any tests since (Travis would trigger such failures but never could get it to reproduce locally). But it's not been the issue the last few times I dug into this with users who reported reproduciblity. Usually it's a kernel side problem. What kernel do you see this with and what's you other dependency version pins?
