### ISSUE TITLE
DuplicateOptionError when converting to slides

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/nbconvert#298]
While exporting a notebook to slides via nbconvert, I get the following error related to Pweave's `ptangle` function, apparently:

```
Traceback (most recent call last):
  File "/Users/fonnescj/anaconda3/bin/jupyter-nbconvert", line 7, in <module>
    from nbconvert.nbconvertapp import main
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 99, in <module>
    class NbConvertApp(JupyterApp):
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 179, in NbConvertApp
    """.format(get_export_names()))
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/nbconvert/exporters/export.py", line 210, in get_export_names
    sorted(entrypoints.get_group_named('nbconvert.exporters'))
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/entrypoints.py", line 183, in get_group_named
    for ep in get_group_all(group, path=path):
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/entrypoints.py", line 194, in get_group_all
    for config, distro in iter_files_distros(path=path):
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/entrypoints.py", line 160, in iter_files_distros
    cp.read(path)
  File "/Users/fonnescj/anaconda3/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/Users/fonnescj/anaconda3/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/Users/fonnescj/anaconda3/lib/python3.5/site-packages/Pweave-0.24-py3.5.egg-info/entry_points.txt' [line  4]: option 'ptangle' in section 'console_scripts' already exists
```

I am running Jupyter 4.1.0 on Python 3.5 (Anaconda) on OS X 10.11.3.

**Comment by takluyver** [comment]
Gah, that's annoying. I'm guessing that if you inspect the file mentioned in the error message, it will have duplicate lines starting `ptangle =`

**Comment by takluyver** [comment]
Oh, I see, it has them with different capitalisations, and configparser ignores case by default.

**Comment by takluyver** [comment]
If you update entrypoints now (`pip install --upgrade entrypoints`), this should work.

**Comment by fonnesbeck** [comment]
That did the trick, thanks!
