### ISSUE TITLE
nbconvert fails with TypeError

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbconvert#305]
Running nbconvert 4.2 (installed via pip) from the command line under python 2.7 fails with the following error:

```
$ jupyter nbconvert
Traceback (most recent call last):
  File "/Users/jhamrick/miniconda3/envs/py2/bin/jupyter-nbconvert", line 7, in <module>
    from nbconvert.nbconvertapp import main
  File "/Users/jhamrick/miniconda3/envs/py2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 99, in <module>
    class NbConvertApp(JupyterApp):
  File "/Users/jhamrick/miniconda3/envs/py2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 179, in NbConvertApp
    """.format(get_export_names()))
  File "/Users/jhamrick/miniconda3/envs/py2/lib/python2.7/site-packages/nbconvert/exporters/export.py", line 210, in get_export_names
    sorted(entrypoints.get_group_named('nbconvert.exporters'))
  File "/Users/jhamrick/miniconda3/envs/py2/lib/python2.7/site-packages/entrypoints.py", line 187, in get_group_named
    for ep in get_group_all(group, path=path):
  File "/Users/jhamrick/miniconda3/envs/py2/lib/python2.7/site-packages/entrypoints.py", line 199, in get_group_all
    if group in config:
TypeError: argument of type 'instance' is not iterable
```

It seems to work fine under python 3.

**Comment by takluyver** [comment]
This comes up if you have python-future in the env, see PythonCharmers/python-future#118 and takluyver/entrypoints#3. I'm trying to work out a workaround in entrypoints, but for now removing `future` is an easy workaround.

**Comment by qingkaikong** [comment]
I also have this problem, and I removed future. But seems the problem is still there for some reason.

**Comment by dmrodriqu** [comment]
having the same problem. I'm not using future

**Comment by qingkaikong** [comment]
The work around provided [here](https://github.com/takluyver/entrypoints/issues/3) solved my problem! Thanks!

**Comment by takluyver** [comment]
A new release of the `configparser` backport has enabled me to fix this in `entrypoints`, and I have done a release of that as well (0.2.2). Upgrading those two packages should resolve this issue.

**Comment by vgoklani** [comment]
Thanks @takluyver
