### ISSUE TITLE
Slides broken?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/nbconvert#344]
When I try to create a reveal slideshow i get a whole bunch of errors thrown and it doesn't display properly. Is the slideshow functionality broken?

I've uploaded my test notebook to: https://anaconda.org/dhirschfeld/test_presentation/notebook

```
λ jupyter nbconvert --to slides test_presentation.ipynb --post serve
[NbConvertApp] Converting notebook test_presentation.ipynb to slides
[NbConvertApp] Writing 274951 bytes to test_presentation.slides.html
[NbConvertApp] Redirecting reveal.js requests to https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0
Serving your slides at http://127.0.0.1:8000/test_presentation.slides.html
Use Control-C to stop this server
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.00ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/css/reveal.css (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/css/reveal.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'Accept': 'text/css,*/*;q=0.1', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\nbconvert\postprocessors\serve.py", line 31, in finish_get
    response.rethrow()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\httpclient.py", line 587, in rethrow
    raise self.error
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:tornado.access:500 GET /reveal.js/css/reveal.css (127.0.0.1) 5272.53ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/css/theme/simple.css (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/css/theme/simple.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'Accept': 'text/css,*/*;q=0.1', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\nbconvert\postprocessors\serve.py", line 31, in finish_get
    response.rethrow()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\httpclient.py", line 587, in rethrow
    raise self.error
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:tornado.access:500 GET /reveal.js/css/theme/simple.css (127.0.0.1) 5018.50ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.00ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/lib/js/head.min.js (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/lib/js/head.min.js', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'Accept': '*/*', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\nbconvert\postprocessors\serve.py", line 31, in finish_get
    response.rethrow()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\httpclient.py", line 587, in rethrow
    raise self.error
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:tornado.access:500 GET /reveal.js/lib/js/head.min.js (127.0.0.1) 5003.50ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/js/reveal.js (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/js/reveal.js', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'Accept': '*/*', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\nbconvert\postprocessors\serve.py", line 31, in finish_get
    response.rethrow()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\httpclient.py", line 587, in rethrow
    raise self.error
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:tornado.access:500 GET /reveal.js/js/reveal.js (127.0.0.1) 5003.50ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.00ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/css/reveal.css (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/css/reveal.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'Accept': 'text/css,*/*;q=0.1', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\nbconvert\postprocessors\serve.py", line 31, in finish_get
    response.rethrow()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\httpclient.py", line 587, in rethrow
    raise self.error
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:tornado.access:500 GET /reveal.js/css/reveal.css (127.0.0.1) 4997.50ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/css/theme/simple.css (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/css/theme/simple.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'Accept': 'text/css,*/*;q=0.1', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\nbconvert\postprocessors\serve.py", line 31, in finish_get
    response.rethrow()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\httpclient.py", line 587, in rethrow
    raise self.error
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:tornado.access:500 GET /reveal.js/css/theme/simple.css (127.0.0.1) 5014.50ms
WARNING:tornado.access:404 GET /style.min.css.map (127.0.0.1) 1.00ms
```

**Comment by dhirschfeld** [comment]
![image](https://cloud.githubusercontent.com/assets/881019/17127055/fcf14848-5345-11e6-8b6c-b375b23cff1a.png)

**Comment by takluyver** [comment]
I don't think it's broken, but it does by default use reveal.js from a CDN. Is it possible that you were offline when you did this? Or maybe the CDN was down.

There is an option to use a local copy of reveal instead.

**Comment by dhirschfeld** [comment]
Not sure if it's significant, but I get a 403 forbidden from the cdn url:
https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0

Is anyone else seeing that or is it just me?

I'm behind a corporate firewall but I have my `HTTP_PROXY` and `HTTPS_PROXY` env vars set and when I navigate to the cdn url the 403 is coming from an nginx (external) server rather than our proxy.

I'll try a local reveal to see if that works for me...

**Comment by dhirschfeld** [comment]
A local install of reveal did work. It would be nice for the cdn to work so if others are also seeing problems with it this issue could be kept open. If it was just something specific to my particular setup and is working for others I'm happy for this to be closed...

**Comment by dhirschfeld** [comment]
From my browser I can navigate to `https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0/js/reveal.min.js` without error so I thought I would try to override the default reveal cdn location using `--reveal-prefix` but it didn't seem to have any effect? (reveal seemed to be coming from the original location?)
```
λ jupyter nbconvert --to slides --reveal-prefix=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0/js/reveal.min.js --post serve test_presentation.ipynb
[NbConvertApp] Converting notebook test_presentation.ipynb to slides
[NbConvertApp] Writing 275447 bytes to test_presentation.slides.html
[NbConvertApp] Redirecting reveal.js requests to https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0
Serving your slides at http://127.0.0.1:8000/test_presentation.slides.html
Use Control-C to stop this server
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.00ms
ERROR:tornado.application:Uncaught exception GET /reveal.js/css/theme/simple.css (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/css/theme/simple.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Dnt': '1', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Connection': 'keep-alive', 'Accept': 'text/css,*/*;q=0.1', 'Referer': 'http://127.0.0.1:8000/test_presentation.slides.html', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate, sdch'})
Traceback (most recent call last):
<SNIP>
```

**Comment by dhirschfeld** [comment]
It seems the 403 might be a red-herring as the full url https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0/js/reveal.js works fine so I assume nbconvert adds the `/js/reveal.js` part at the end.

Specifying `--reveal-prefix=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0` also seems to be ignored but the js library doesn't seem to be the issue.

At this stage I'm thinking its possibly something to do with the proxy in which case, as mentioned, I'm happy for this to be closed. I'll try and repro when I'm not behind a proxy to verify but that probably won't happen until next week...

**Comment by takluyver** [comment]
It does add e.g. `/js/reveal.js` to the URL prefix - there are actually several JS and CSS files that it loads from the same prefix. It's concerning if it's ignoring the URL you give at the command line; I wonder if the browser might be caching the slides you produce.

**Comment by mghijs** [comment]
I have a similar issue, which I (wrongly) posted [here](https://github.com/Anaconda-Platform/nbpresent/issues/82#issuecomment-236585112) in the `nbpresent` repo.
It used to work fine until I updated Anaconda and every package in it.

**Comment by michaelpacer** [comment]
@mghijs did the local install of reveal work for you?

**Comment by mghijs** [comment]
@michaelpacer thanks for the suggestion, it didn't work either though and gave me this error message:
```c++
jupyter nbconvert general_info.ipynb --to slides --post serve
[NbConvertApp] Converting notebook general_info.ipynb to slides
[NbConvertApp] Writing 392021 bytes to general_info.slides.html
[NbConvertApp] Serving local reveal.js
Serving your slides at http://127.0.0.1:8000/general_info.slides.html
Use Control-C to stop this server
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 3.00ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.00ms
```

**Comment by damianavila** [comment]
One more question @mghijs, are you running from master or last release?

**Comment by mghijs** [comment]
I was running from master, but just tried the reveal.js-3.3.0 release and that gave the same result.

**Comment by damianavila** [comment]
@dhirschfeld, I tried with latest nbconvert (5.2.1) and I can not reproduce your issue. Can you test it again with latest released version and see if you still see the issue?

@mghijs, those 404 for custom.css are not harmful, can you also try with latest nbconvert and see if you still see the issue? 

Thanks.

**Comment by damianavila** [comment]
I could not replicate this issue, so I will close it now.
@dhirschfeld feel free to reopen if you still see this with master so we can further debug.

**Comment by abjer** [comment]
I have the issue when using nbconvert on my Win10 machine but not on my Linux virtual box.

On my Win10 machine I use 64bit OS and miniconda. 

Both machines run nbconvert 5.2.1.

On the Linux machine I do not get the favicon error but on the windows machine I do.
