### ISSUE TITLE
ImportError: No module named jupyter_client.manager

### ISSUE THREAD

**Issue by stefanw** [jupyter/nbconvert#495]
In a fresh environment:

```
$ pip install nbconvert
$ python -c "import nbconvert"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lib/python2.7/site-packages/nbconvert/__init__.py", line 6, in <module>
    from . import preprocessors
  File "lib/python2.7/site-packages/nbconvert/preprocessors/__init__.py", line 10, in <module>
    from .execute import ExecutePreprocessor
  File "lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 21, in <module>
    from jupyter_client.manager import KernelManager
ImportError: No module named jupyter_client.manager
```

So without the `extras_require` named `execute` `nbconvert` crashes on import time.

**Comment by takluyver** [comment]
Thanks, I've opened #499 to address this.
