### ISSUE TITLE
ImportError: No module named jupyter_contrib_nbextensions.nbconvert_support

### ISSUE THREAD

**Issue by dpsanders** [jupyter/nbconvert#526]
On a clean installation, I get the following error.
(Note that Julia uses Conda to install Jupyter.)
```
15:29 $ jupyter nbconvert MyNotebook.ipynb
Traceback (most recent call last):
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/bin/jupyter-nbconvert", line 6, in <module>
    main()
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 447, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 151, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 101, in __init__
    self._init_preprocessors()
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 250, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 211, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
  File "/Users/dpsanders/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named jupyter_contrib_nbextensions.nbconvert_support
```

**Comment by juhasch** [comment]
This looks like you have a configuration file that tries to import from the (not installed) `jupyter_contrib_nbextensions` package.
Can you take a look at the `jupyter_nbconvert_config.json`file ?
Possible locations of this file can be found under `config` when you call `jupyter --path`.

**Comment by dpsanders** [comment]
Indeed, there was a `jupyter_nbconvert_config.json` file.
Moving it out of the way solved the issue; many thanks!

**Comment by Senui** [comment]
This seems to happen in the following case too:

1. User has a configuration file in one of the default config paths of jupyter
2. User initializes a virtual python environment (e.g. with pyenv)
3. User uses nbconvert, which picks up the configuration file that uses a pip package that was only available on the host system's python, but not in the virtual python environment

Is there a cleaner way than simply deleting that configuration file? I am a bit surprised that the virtual environment picks up on this configuration file. Is there a way to ignore any configuration files perhaps?

**Comment by EJFielding** [comment]
I ran into this same problem. My `$HOME/.jupyter/` directory had two files `jupyter_nbconvert_config.json` and `jupyter_notebook_config.json` that both pointed to an older (Python 3.6) path for the templates. I had to delete them to get `jupyter nbconvert` and exporting from inside `jupyter notebook` to run correctly.

**Comment by lassebenni** [comment]
> I ran into this same problem. My `$HOME/.jupyter/` directory had two files `jupyter_nbconvert_config.json` and `jupyter_notebook_config.json` that both pointed to an older (Python 3.6) path for the templates, which I had removed when Python 3.6 was obsolete. I had to delete them to get `jupyter nbconvert` and exporting from inside `jupyter notebook` to run correctly.

Thank you! That saved me a lot of work.

**Comment by AllenDowney** [comment]
I ran into this problem today, and it took me a long time to find this thread and fix it.

This seems like pretty bad behavior -- it seems like it would be good to fix it if possible, or if not, catch this error and provide instructions for removing old config files (or a link to this thread).

**Comment by nilcam** [comment]
> I ran into this problem today, and it took me a long time to find this thread and fix it.
> 
> This seems like pretty bad behavior -- it seems like it would be good to fix it if possible, or if not, catch this error and provide instructions for removing old config files (or a link to this thread).

Same here, it took a long time for me to find this fix.
