### ISSUE TITLE
Add aliases for export formats [feature-request]

### ISSUE THREAD

**Issue by demidovakatya** [jupyter/nbconvert#536]
Hi, 

This is a minor feature request. (And I think I'll even implement it by myself when I have enough time.)

I typed in `$ jupyter-nbconvert --to md notebook_name.ipynb` (which seems totally ok to me) and got this:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 305, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 462, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/base.py", line 110, in get_exporter
    % (name, ', '.join(get_export_names())))
ValueError: Unknown exporter "md", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
```

I think, if there were aliases for some of the export formats (like `markdown` -> `md` or `python` -> `py`), it would be better. :)

**Comment by michaelpacer** [comment]
This is an interesting idea; the issue with doing something like this is that it may need to occur at installation time (because entrypoints are set in place at installation time and exporter names are specified via entrypoints). That would require reinstalling nbconvert every time you want to change those settings, and that seems suboptimal.

@takluyver @Carreau @minrk Can you think of any way to set aliases like this that are recognised as entrypoints that won't require a reinstallation step to register every configuration change?

**Comment by minrk** [comment]
We could define aliases separately from entrypoints, so that they get expanded prior to the entrypoint lookup.

**Comment by takluyver** [comment]
Yup. We could very easily have a hardcoded dict mapping abbreviations to full names, and with only slightly more difficulty that could be a config option on `nbconvertapp`.

**Comment by demidovakatya** [comment]
> That would require reinstalling nbconvert every time you want to change those settings, and that seems suboptimal.

Being honest, I wouldn't make these aliases easily configurable. I mean, adding something like file extensions to this list: `asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?` looks more than enough.

(On the other hand, your idea looks better.)
