### ISSUE TITLE
--ExecutePreprocessor.timeout doesn't work with None

### ISSUE THREAD

**Issue by jabellcu** [jupyter/nbconvert#551]
[https://nbconvert.readthedocs.io/en/latest/config_options.html](url) states:

> None or -1 will disable the timeout. If timeout_func is set, it overrides timeout.

for `ExecutePreprocessor.timeout`, but it doesn't really work for `None`. I get the following message:

```
$  jupyter nbconvert --to=notebook --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=None --NbConvertApp.use_output_suffix=False --execute test.ipynb

[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python
Traceback (most recent call last):
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\Scripts\jupyter-nbconvert-script.py", line 5, in <module>
    main()
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 428, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\exporters\notebook.py", line 26, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\preprocessors\execute.py", line 145, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\preprocessors\base.py", line 70, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\preprocessors\execute.py", line 161, in preprocess_cell
    outputs = self.run_cell(cell)
  File "C:\Users\UserX\AppData\Local\Continuum\Anaconda3\lib\site-packages\nbconvert\preprocessors\execute.py", line 187, in run_cell
    if timeout < 0:
TypeError: unorderable types: NoneType() < int()

```

It does work if I use -1, though :-)

**Comment by mpacer** [comment]
That is…strange, I think you might be using an old version of nbconvert. Your line number isn't "correct" for where that comparison is happening (should be 265 not 187).

Additionally, if you look at that line [in the codebase](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L265) you'll see that it says `if not timeout or timeout < 0:` not `if timeout < 0` (which would trigger the error you're seeing with `None`). 

Happy to answer questions, but closing.
