### ISSUE TITLE
Error converting to PDF: 'FileNotFoundError ' is not defined

### ISSUE THREAD

**Issue by avonmoll** [jupyter/nbconvert#731]
Versions:
- Windows 7, 64 bit
- python 2.7.11
- jupyter 4.4.0
- nbconvert 5.3.1
- MiKTeX 2.9

I've called nbconvert on a notebook like this:

`jupyter nbconvert --to pdf notebook.ipynb`

which results in this error:

```
[NbConvertApp] Converting notebook 2p1e.ipynb to pdf
Traceback (most recent call last):
  File "C:\Program Files\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Program Files\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\Scripts\jupyter-nbconvert.EXE\__main__.py", line 9, in <module>
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\nbconvertapp.py", line 493, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\nbconvertapp.py", line 464, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\pdf.py", line 162, in from_notebook_node
    nb, resources=resources, **kw
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\latex.py", line 82, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\templateexporter.py", line 280, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\exporters\exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\preprocessors\convertfigures.py", line 46, in preprocess_cell
    self.from_format, output.data[self.from_format])
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 91, in convert_figure
    shell = self.command.format(from_filename=input_filename,
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 55, in _command_default
    return self.inkscape + \
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\users\vonmolal\appdata\local\enthought\canopy\user\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 69, in _inkscape_default
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

Based on a cursory search, it seems to me that `FileNotFoundError` doesn't exist in Python 2.7. Did I mess something up and somehow get a version of Jupyter / Nbconvert that is only compatible with Python 3?

**Comment by takluyver** [comment]
I think that's a genuine bug - there will be a Python 3 only version of nbconvert at some point, but we haven't done it yet. Though the fact that this has been undetected for a couple of years is a good sign for that move.

In the meantime, feel free to make a PR to fix it for Python 2.

**Comment by zaninip** [comment]
Hi.
I have the same problem (with python 2.7.13). Do you have any news if the bug has been solved for Python 2?
