### ISSUE TITLE
UnicodeDecodeError when converting to slides on Windows

### ISSUE THREAD

**Issue by HagaiHargil** [jupyter/nbconvert#742]
Hi,

I'm having issues converting my notebooks to slides. The error is the following:

```
(general) PS C:\Users\Hagai\Documents\Classes\python-course\Classes> jupyter nbconvert class3.ipynb --to slides --post serve
[NbConvertApp] Converting notebook class3.ipynb to slides
Traceback (most recent call last):
  File "C:\Users\Hagai\Miniconda3\envs\general\Scripts\jupyter-nbconvert-script.py", line 5, in <module>
    exit(main())
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\nbconvertapp.py", line 493, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\nbconvertapp.py", line 464, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\slides.py", line 172, in from_notebook_node
    return super(SlidesExporter, self).from_notebook_node(nb, resources=resources, **kw)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\html.py", line 85, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\templateexporter.py", line 280, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\exporters\exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\preprocessors\csshtmlheader.py", line 52, in preprocess
    resources['inlining']['css'] = self._generate_header(resources)
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\preprocessors\csshtmlheader.py", line 127, in _generate_header
    if self._hash(custom_css_filename) != self._default_css_hash:
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\site-packages\nbconvert\preprocessors\csshtmlheader.py", line 136, in _hash
    md5.update(str_to_bytes(f.read()))
  File "C:\Users\Hagai\Miniconda3\envs\general\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5555: character maps to <undefined>
```

Converting the same notebook to a PDF, for example, raises no errors. It does seem like this conversion tries to use the `cp1252` Windows encoding, but I'm not sure exactly how to change it to UTF-8, and whether it could help me resolve the issue.

I'm using Windows 10 and Python 3.6.4, with Jupyter version 1.0.0 and `nbconvert` 5.3.1.

**Comment by mpacer** [comment]
Do you want to try to contribute the fix? I don’t have a windows machine and so can guide you on what I think the important parts might be but cannot debug this myself.

**Comment by HagaiHargil** [comment]
Sure thing!
I'm not sure how much free time I'll have in the coming weeks, but I'm willing to give it a shot.

**Comment by HagaiHargil** [comment]
@mpacer I have a bit more time now. Any useful starting tips? :)

**Comment by takluyver** [comment]
The code that the error is coming from is calculating the md5 hash of a file. That's something that shouldn't involve unicode at all, because hashing processes bytes, not characters. We can read the file as bytes by passing the `'b'` flag to the open function, like `open(filename, 'rb')`. Does that help you start with this?

**Comment by HagaiHargil** [comment]
Thanks!

#757 was created.

**Comment by mpacer** [comment]
Hi @HagaiHargil hadn't seen this, but great to see that you've got a PR open. I'll go review it now!
