### ISSUE TITLE
import nbconvert or nbformat causes importing pip 9.0.2 to fail

### ISSUE THREAD

**Issue by drmattyg** [jupyter/nbconvert#783]
Python version 3.5.2
nbconvert==5.3.1
nbformat==4.4.0
pip==9.0.2
Repro:
```
import nbconvert
import pip
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.virtualenv/production/lib/python3.5/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/.virtualenv/production/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/.virtualenv/production/lib/python3.5/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/.virtualenv/production/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/home/ubuntu/.virtualenv/production/lib/python3.5/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```
Details:
This bug is only exposed by pip 9.0.2, and does not occur under pip 9.0.1. No other packages I'm working with right now cause this problem with importing pip.  Unclear to me whose fault this is, but since everybody and their brother is going to upgrade pip pretty soon, this might be something to look at.

**Comment by drmattyg** [comment]
Here's the corresponding pip issue:
https://github.com/pypa/pip/issues/5079

**Comment by drmattyg** [comment]
I'm seeing this is primarily an issue with `pip` and them basically saying FU to anybody who actually imports the package, so I'll go ahead and close this.
