### ISSUE TITLE
tornado >= 6 dependency breaks nbconvert behavior

### ISSUE THREAD

**Issue by DavidJVitale** [jupyter/nbconvert#978]
Looks like `tornado >= 6` has some breaking changes. Reproducible on Windows and OSX, I have `nbconvert==5.4.0` and `tornado==6.0.2`. [Full conda env can be viewed here](https://github.com/jupyter/nbconvert/files/3039941/full_conda_env_nbconvert_bug.txt)

```bash
(geosaurus_dev_env) ~ $ jupyter nbconvert ./Untitled.ipynb 
Traceback (most recent call last):
  File "/Users/davi9349/anaconda3/envs/geosaurus_dev_env/bin/jupyter-nbconvert", line 7, in <module>
    from nbconvert.nbconvertapp import main
  File "/Users/davi9349/anaconda3/envs/geosaurus_dev_env/lib/python3.6/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/Users/davi9349/anaconda3/envs/geosaurus_dev_env/lib/python3.6/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/Users/davi9349/anaconda3/envs/geosaurus_dev_env/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/Users/davi9349/anaconda3/envs/geosaurus_dev_env/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

If I downgrade to a `5.X.X` of `tornado` this issue goes away.

**Comment by DavidJVitale** [comment]
Relevant info from [the related thread](https://github.com/tornadoweb/tornado/issues/2641#issuecomment-479616190):

> Yes, removing `web.asynchronous` was intentional:
> 
> https://www.tornadoweb.org/en/branch5.1/web.html#tornado.web.asynchronous
> 
> > Deprecated since version 5.1: This decorator is deprecated and will be removed in Tornado 6.0. Use coroutines instead.

**Comment by MSeal** [comment]
@DavidJVitale This is fixed on master. We'll be releasing 5.5 in a week or two with support for tornado >=6.0
