### ISSUE TITLE
Failure converting to LaTeX

### ISSUE THREAD

**Issue by boffi** [jupyter/nbconvert#981]
HTML conversion is fine, latex fails in a way that I find obscure.
All my notebooks (oh well, the five I've tested) trigger the same behaviour, so I guess it's not a problem of a particular notebook.

I have an up to date anaconda distribution on Debian Sid.

Here follows the backtrace from nbconvert:

```
23:39 boffi@debian:~/.../hw02 $ jupyter nbconvert Homework2.ipynb 
[NbConvertApp] Converting notebook Homework2.ipynb to html
[NbConvertApp] Writing 627605 bytes to Homework2.html
23:40 boffi@debian:~/.../hw02 $ jupyter nbconvert --to latex Homework2.ipynb
[NbConvertApp] Converting notebook Homework2.ipynb to latex
Traceback (most recent call last):
  File "/home/boffi/lib/miniconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/latex.py", line 84, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 300, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 138, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 315, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/boffi/lib/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/extractoutput.py", line 92, in preprocess_cell
    data = json.dumps(data)
  File "/home/boffi/lib/miniconda3/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/boffi/lib/miniconda3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/boffi/lib/miniconda3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/boffi/lib/miniconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
23:40 boffi@debian:~/.../hw02 $ 
```

**Comment by MSeal** [comment]
Can you attach your notebook that failed? I don't get the same error with py3.7 with a trivial example. Also was this with nbconvert 5.4 (looks like it was)?

I'm not that familiar with the latex exporter but it looks like something was returning binary instead of string data for python 3. I'm guessing based on the exception you hit that it might succeed in python 2.7.

**Comment by boffi** [comment]
I said, not a problem with a particular notebook... well, not with a particular notebook of mine, because in every notebook I use the magic `%config InlineBackend.figure_formats = ['svg']` and it seems that a notebook w/o SVG inlined id correctly converted, while if I have plots in vector format I have a failure.
@MSeal I attach a minimal notebook that fails to convert. Thank you.

[Untitled.txt](https://github.com/jupyter/nbconvert/files/3051413/Untitled.txt)

**Comment by MSeal** [comment]
Thanks for the example @boffi -- it was indeed a python 3 specific issue with upstream libraries returning data in python 2 string format. Until this releases, python 2 conversions do work fyi. I've linked the PR for the upcoming release.
